CREATE TABLE VIEW_LIQUIDACION (
NUMERO_RECIBO VARCHAR2 (10), 
NUMERO_FACTURA VARCHAR2 (20), 
ID_TIPO_DOCUMENTO NUMERIC,
TIPO_DOCUMENTO VARCHAR2 (20), 
IDENTIFICACION VARCHAR2 (20), 
ID_ESTADO NUMERIC,
ESTADO VARCHAR2 (20), 
FECHA_LIQUIDACION DATETIME, 
FECHA_PAGO DATETIME,
ID_TIPO_LIQUIDACION NUMERIC, 
TIPO VARCHAR2 (12), 
TARIFA VARCHAR2 (20)
CONSTRAINT PRIMARY KEY (NUMERO_RECIBO)
)