//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaConduccion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosDEPARTAMENTO.asmx")]
        public string EscuelaConduccion_wsServiciosDEPARTAMENTO_ServiciosDEPARTAMENTO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosDEPARTAMENTO_ServiciosDEPARTAMENTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosCIUDAD.asmx")]
        public string EscuelaConduccion_wsServiciosCIUDAD_ServiciosCIUDAD {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosCIUDAD_ServiciosCIUDAD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosVIEW_CIUDAD.asmx")]
        public string EscuelaConduccion_wsServiciosVIEW_CIUDAD_ServiciosVIEW_CIUDAD {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosVIEW_CIUDAD_ServiciosVIEW_CIUDAD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosCLIENTE.asmx")]
        public string EscuelaConduccion_wsServiciosCLIENTE_ServiciosCLIENTE {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosCLIENTE_ServiciosCLIENTE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosVIEW_CLIENTE.asmx")]
        public string EscuelaConduccion_wsServiciosVIEW_CLIENTE_ServiciosVIEW_CLIENTE {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosVIEW_CLIENTE_ServiciosVIEW_CLIENTE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosTIPO_DOCUMENTO.asmx")]
        public string EscuelaConduccion_wsServiciosTIPO_DOCUMENTO_ServiciosTIPO_DOCUMENTO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosTIPO_DOCUMENTO_ServiciosTIPO_DOCUMENTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosGENERO.asmx")]
        public string EscuelaConduccion_wsServiciosGENERO_ServiciosGENERO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosGENERO_ServiciosGENERO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosTARIFA.asmx")]
        public string EscuelaConduccion_wsServiciosTARIFA_ServiciosTARIFA {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosTARIFA_ServiciosTARIFA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosTARIFA_DETALLE.asmx")]
        public string EscuelaConduccion_wsServiciosTARIFA_DETALLE_ServiciosTARIFA_DETALLE {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosTARIFA_DETALLE_ServiciosTARIFA_DETALLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosVIGENCIA.asmx")]
        public string EscuelaConduccion_wsServiciosVIGENCIA_ServiciosVIGENCIA {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosVIGENCIA_ServiciosVIGENCIA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosLIQUIDACION_DETALLE.asmx")]
        public string EscuelaConduccion_wsServiciosLIQUIDACION_DETALLE_ServiciosLIQUIDACION_DETALLE {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosLIQUIDACION_DETALLE_ServiciosLIQUIDACION_DETALLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosTIPO_LIQUIDACION.asmx")]
        public string EscuelaConduccion_wsServiciosTIPO_LIQUIDACION_ServiciosTIPO_LIQUIDACION {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosTIPO_LIQUIDACION_ServiciosTIPO_LIQUIDACION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosLIQUIDACION.asmx")]
        public string EscuelaConduccion_wsServiciosLIQUIDACION_ServiciosLIQUIDACION {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosLIQUIDACION_ServiciosLIQUIDACION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosRECIBO.asmx")]
        public string EscuelaConduccion_WSServiciosRECIBO_ServiciosRECIBO {
            get {
                return ((string)(this["EscuelaConduccion_WSServiciosRECIBO_ServiciosRECIBO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosRECIBO_ESTADO.asmx")]
        public string EscuelaConduccion_wsServiciosRECIBO_ESTADO_ServiciosRECIBO_ESTADO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosRECIBO_ESTADO_ServiciosRECIBO_ESTADO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosFACTURACONSECUTIVO.asmx")]
        public string EscuelaConduccion_wsServiciosFACTURACONSECUTIVO_ServiciosFACTURACONSECUTIVO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosFACTURACONSECUTIVO_ServiciosFACTURACONSECUTIVO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosViewrecibo.asmx")]
        public string EscuelaConduccion_wsServiciosViewrecibo_ServiciosViewrecibo {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosViewrecibo_ServiciosViewrecibo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosFormadepago.asmx")]
        public string EscuelaConduccion_WSServiciosFormadepago_ServiciosFormadepago {
            get {
                return ((string)(this["EscuelaConduccion_WSServiciosFormadepago_ServiciosFormadepago"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosPagos.asmx")]
        public string EscuelaConduccion_wsServiciosPagos_ServiciosPagos {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosPagos_ServiciosPagos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosFacturaconsecutivodetalle.asmx")]
        public string EscuelaConduccion_wsServiciosFacturaconsecutivodetalle_ServiciosFacturaconsecutivodetalle {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosFacturaconsecutivodetalle_ServiciosFacturaconsecutiv" +
                    "odetalle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosFACTURA.asmx")]
        public string EscuelaConduccion_wsServiciosFACTURA_ServiciosFACTURA {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosFACTURA_ServiciosFACTURA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosSQL.asmx")]
        public string EscuelaConduccion_wsServiciosSQL_ServiciosSQL {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosSQL_ServiciosSQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosACUERDO_PAGO_DETALLE.asmx")]
        public string EscuelaConduccion_wsServiciosACUERDO_PAGO_DETALLE_ServiciosACUERDO_PAGO_DETALLE {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosACUERDO_PAGO_DETALLE_ServiciosACUERDO_PAGO_DETALLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosACUERDO_ESTADO.asmx")]
        public string EscuelaConduccion_wsServiciosACUERDO_ESTADO_ServiciosACUERDO_ESTADO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosACUERDO_ESTADO_ServiciosACUERDO_ESTADO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosACUERDO_PAGO.asmx")]
        public string EscuelaConduccion_wsServiciosACUERDO_PAGO_ServiciosACUERDO_PAGO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosACUERDO_PAGO_ServiciosACUERDO_PAGO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosFACTURA_ESTADO.asmx")]
        public string EscuelaConduccion_wsServiciosFACTURA_ESTADO_ServiciosFACTURA_ESTADO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosFACTURA_ESTADO_ServiciosFACTURA_ESTADO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosViewliquidacion.asmx")]
        public string EscuelaConduccion_wsServiciosViewliquidacion_ServiciosViewliquidacion {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosViewliquidacion_ServiciosViewliquidacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosTARIFACATEGORIA.asmx")]
        public string EscuelaConduccion_wsServiciosTARIFACATEGORIA_ServiciosTARIFACATEGORIA {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosTARIFACATEGORIA_ServiciosTARIFACATEGORIA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:52393/Model/Services/ServiciosTARIFA_CONCEPTO.asmx")]
        public string EscuelaConduccion_wsServiciosTARIFA_CONCEPTO_ServiciosTARIFA_CONCEPTO {
            get {
                return ((string)(this["EscuelaConduccion_wsServiciosTARIFA_CONCEPTO_ServiciosTARIFA_CONCEPTO"]));
            }
        }
    }
}
