//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosACUERDO_ESTADO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosACUERDO_ESTADOSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosACUERDO_ESTADO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearACUERDO_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarACUERDO_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroACUERDO_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarACUERDO_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarACUERDO_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarACUERDO_ESTADOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosACUERDO_ESTADO() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosACUERDO_ESTADO_ServiciosACUERDO_ESTADO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearACUERDO_ESTADOCompletedEventHandler crearACUERDO_ESTADOCompleted;
        
        /// <remarks/>
        public event editarACUERDO_ESTADOCompletedEventHandler editarACUERDO_ESTADOCompleted;
        
        /// <remarks/>
        public event buscarPrimeroACUERDO_ESTADOCompletedEventHandler buscarPrimeroACUERDO_ESTADOCompleted;
        
        /// <remarks/>
        public event buscarACUERDO_ESTADOCompletedEventHandler buscarACUERDO_ESTADOCompleted;
        
        /// <remarks/>
        public event listarACUERDO_ESTADOCompletedEventHandler listarACUERDO_ESTADOCompleted;
        
        /// <remarks/>
        public event eliminarACUERDO_ESTADOCompletedEventHandler eliminarACUERDO_ESTADOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearACUERDO_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_ESTADO crearACUERDO_ESTADO(ACUERDO_ESTADO obj) {
            object[] results = this.Invoke("crearACUERDO_ESTADO", new object[] {
                        obj});
            return ((ACUERDO_ESTADO)(results[0]));
        }
        
        /// <remarks/>
        public void crearACUERDO_ESTADOAsync(ACUERDO_ESTADO obj) {
            this.crearACUERDO_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearACUERDO_ESTADOAsync(ACUERDO_ESTADO obj, object userState) {
            if ((this.crearACUERDO_ESTADOOperationCompleted == null)) {
                this.crearACUERDO_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearACUERDO_ESTADOOperationCompleted);
            }
            this.InvokeAsync("crearACUERDO_ESTADO", new object[] {
                        obj}, this.crearACUERDO_ESTADOOperationCompleted, userState);
        }
        
        private void OncrearACUERDO_ESTADOOperationCompleted(object arg) {
            if ((this.crearACUERDO_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearACUERDO_ESTADOCompleted(this, new crearACUERDO_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarACUERDO_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarACUERDO_ESTADO(ACUERDO_ESTADO obj) {
            object[] results = this.Invoke("editarACUERDO_ESTADO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarACUERDO_ESTADOAsync(ACUERDO_ESTADO obj) {
            this.editarACUERDO_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarACUERDO_ESTADOAsync(ACUERDO_ESTADO obj, object userState) {
            if ((this.editarACUERDO_ESTADOOperationCompleted == null)) {
                this.editarACUERDO_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarACUERDO_ESTADOOperationCompleted);
            }
            this.InvokeAsync("editarACUERDO_ESTADO", new object[] {
                        obj}, this.editarACUERDO_ESTADOOperationCompleted, userState);
        }
        
        private void OneditarACUERDO_ESTADOOperationCompleted(object arg) {
            if ((this.editarACUERDO_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarACUERDO_ESTADOCompleted(this, new editarACUERDO_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroACUERDO_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_ESTADO buscarPrimeroACUERDO_ESTADO(ACUERDO_ESTADO obj) {
            object[] results = this.Invoke("buscarPrimeroACUERDO_ESTADO", new object[] {
                        obj});
            return ((ACUERDO_ESTADO)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroACUERDO_ESTADOAsync(ACUERDO_ESTADO obj) {
            this.buscarPrimeroACUERDO_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroACUERDO_ESTADOAsync(ACUERDO_ESTADO obj, object userState) {
            if ((this.buscarPrimeroACUERDO_ESTADOOperationCompleted == null)) {
                this.buscarPrimeroACUERDO_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroACUERDO_ESTADOOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroACUERDO_ESTADO", new object[] {
                        obj}, this.buscarPrimeroACUERDO_ESTADOOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroACUERDO_ESTADOOperationCompleted(object arg) {
            if ((this.buscarPrimeroACUERDO_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroACUERDO_ESTADOCompleted(this, new buscarPrimeroACUERDO_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarACUERDO_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_ESTADO[] buscarACUERDO_ESTADO(ACUERDO_ESTADO obj) {
            object[] results = this.Invoke("buscarACUERDO_ESTADO", new object[] {
                        obj});
            return ((ACUERDO_ESTADO[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarACUERDO_ESTADOAsync(ACUERDO_ESTADO obj) {
            this.buscarACUERDO_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarACUERDO_ESTADOAsync(ACUERDO_ESTADO obj, object userState) {
            if ((this.buscarACUERDO_ESTADOOperationCompleted == null)) {
                this.buscarACUERDO_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarACUERDO_ESTADOOperationCompleted);
            }
            this.InvokeAsync("buscarACUERDO_ESTADO", new object[] {
                        obj}, this.buscarACUERDO_ESTADOOperationCompleted, userState);
        }
        
        private void OnbuscarACUERDO_ESTADOOperationCompleted(object arg) {
            if ((this.buscarACUERDO_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarACUERDO_ESTADOCompleted(this, new buscarACUERDO_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarACUERDO_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_ESTADO[] listarACUERDO_ESTADO() {
            object[] results = this.Invoke("listarACUERDO_ESTADO", new object[0]);
            return ((ACUERDO_ESTADO[])(results[0]));
        }
        
        /// <remarks/>
        public void listarACUERDO_ESTADOAsync() {
            this.listarACUERDO_ESTADOAsync(null);
        }
        
        /// <remarks/>
        public void listarACUERDO_ESTADOAsync(object userState) {
            if ((this.listarACUERDO_ESTADOOperationCompleted == null)) {
                this.listarACUERDO_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarACUERDO_ESTADOOperationCompleted);
            }
            this.InvokeAsync("listarACUERDO_ESTADO", new object[0], this.listarACUERDO_ESTADOOperationCompleted, userState);
        }
        
        private void OnlistarACUERDO_ESTADOOperationCompleted(object arg) {
            if ((this.listarACUERDO_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarACUERDO_ESTADOCompleted(this, new listarACUERDO_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarACUERDO_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarACUERDO_ESTADO(ACUERDO_ESTADO obj) {
            object[] results = this.Invoke("eliminarACUERDO_ESTADO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarACUERDO_ESTADOAsync(ACUERDO_ESTADO obj) {
            this.eliminarACUERDO_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarACUERDO_ESTADOAsync(ACUERDO_ESTADO obj, object userState) {
            if ((this.eliminarACUERDO_ESTADOOperationCompleted == null)) {
                this.eliminarACUERDO_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarACUERDO_ESTADOOperationCompleted);
            }
            this.InvokeAsync("eliminarACUERDO_ESTADO", new object[] {
                        obj}, this.eliminarACUERDO_ESTADOOperationCompleted, userState);
        }
        
        private void OneliminarACUERDO_ESTADOOperationCompleted(object arg) {
            if ((this.eliminarACUERDO_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarACUERDO_ESTADOCompleted(this, new eliminarACUERDO_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ACUERDO_ESTADO {
        
        private int idField;
        
        private string nOMBREField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearACUERDO_ESTADOCompletedEventHandler(object sender, crearACUERDO_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearACUERDO_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearACUERDO_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_ESTADO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_ESTADO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarACUERDO_ESTADOCompletedEventHandler(object sender, editarACUERDO_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarACUERDO_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarACUERDO_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroACUERDO_ESTADOCompletedEventHandler(object sender, buscarPrimeroACUERDO_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroACUERDO_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroACUERDO_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_ESTADO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_ESTADO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarACUERDO_ESTADOCompletedEventHandler(object sender, buscarACUERDO_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarACUERDO_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarACUERDO_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_ESTADO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_ESTADO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarACUERDO_ESTADOCompletedEventHandler(object sender, listarACUERDO_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarACUERDO_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarACUERDO_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_ESTADO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_ESTADO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarACUERDO_ESTADOCompletedEventHandler(object sender, eliminarACUERDO_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarACUERDO_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarACUERDO_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591