//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosFACTURA_ESTADO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosFACTURA_ESTADOSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosFACTURA_ESTADO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearFACTURA_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarFACTURA_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroFACTURA_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarFACTURA_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarFACTURA_ESTADOOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarFACTURA_ESTADOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosFACTURA_ESTADO() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosFACTURA_ESTADO_ServiciosFACTURA_ESTADO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearFACTURA_ESTADOCompletedEventHandler crearFACTURA_ESTADOCompleted;
        
        /// <remarks/>
        public event editarFACTURA_ESTADOCompletedEventHandler editarFACTURA_ESTADOCompleted;
        
        /// <remarks/>
        public event buscarPrimeroFACTURA_ESTADOCompletedEventHandler buscarPrimeroFACTURA_ESTADOCompleted;
        
        /// <remarks/>
        public event buscarFACTURA_ESTADOCompletedEventHandler buscarFACTURA_ESTADOCompleted;
        
        /// <remarks/>
        public event listarFACTURA_ESTADOCompletedEventHandler listarFACTURA_ESTADOCompleted;
        
        /// <remarks/>
        public event eliminarFACTURA_ESTADOCompletedEventHandler eliminarFACTURA_ESTADOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearFACTURA_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA_ESTADO crearFACTURA_ESTADO(FACTURA_ESTADO obj) {
            object[] results = this.Invoke("crearFACTURA_ESTADO", new object[] {
                        obj});
            return ((FACTURA_ESTADO)(results[0]));
        }
        
        /// <remarks/>
        public void crearFACTURA_ESTADOAsync(FACTURA_ESTADO obj) {
            this.crearFACTURA_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearFACTURA_ESTADOAsync(FACTURA_ESTADO obj, object userState) {
            if ((this.crearFACTURA_ESTADOOperationCompleted == null)) {
                this.crearFACTURA_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearFACTURA_ESTADOOperationCompleted);
            }
            this.InvokeAsync("crearFACTURA_ESTADO", new object[] {
                        obj}, this.crearFACTURA_ESTADOOperationCompleted, userState);
        }
        
        private void OncrearFACTURA_ESTADOOperationCompleted(object arg) {
            if ((this.crearFACTURA_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearFACTURA_ESTADOCompleted(this, new crearFACTURA_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarFACTURA_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarFACTURA_ESTADO(FACTURA_ESTADO obj) {
            object[] results = this.Invoke("editarFACTURA_ESTADO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarFACTURA_ESTADOAsync(FACTURA_ESTADO obj) {
            this.editarFACTURA_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarFACTURA_ESTADOAsync(FACTURA_ESTADO obj, object userState) {
            if ((this.editarFACTURA_ESTADOOperationCompleted == null)) {
                this.editarFACTURA_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarFACTURA_ESTADOOperationCompleted);
            }
            this.InvokeAsync("editarFACTURA_ESTADO", new object[] {
                        obj}, this.editarFACTURA_ESTADOOperationCompleted, userState);
        }
        
        private void OneditarFACTURA_ESTADOOperationCompleted(object arg) {
            if ((this.editarFACTURA_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarFACTURA_ESTADOCompleted(this, new editarFACTURA_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroFACTURA_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA_ESTADO buscarPrimeroFACTURA_ESTADO(FACTURA_ESTADO obj) {
            object[] results = this.Invoke("buscarPrimeroFACTURA_ESTADO", new object[] {
                        obj});
            return ((FACTURA_ESTADO)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroFACTURA_ESTADOAsync(FACTURA_ESTADO obj) {
            this.buscarPrimeroFACTURA_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroFACTURA_ESTADOAsync(FACTURA_ESTADO obj, object userState) {
            if ((this.buscarPrimeroFACTURA_ESTADOOperationCompleted == null)) {
                this.buscarPrimeroFACTURA_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroFACTURA_ESTADOOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroFACTURA_ESTADO", new object[] {
                        obj}, this.buscarPrimeroFACTURA_ESTADOOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroFACTURA_ESTADOOperationCompleted(object arg) {
            if ((this.buscarPrimeroFACTURA_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroFACTURA_ESTADOCompleted(this, new buscarPrimeroFACTURA_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarFACTURA_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA_ESTADO[] buscarFACTURA_ESTADO(FACTURA_ESTADO obj) {
            object[] results = this.Invoke("buscarFACTURA_ESTADO", new object[] {
                        obj});
            return ((FACTURA_ESTADO[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarFACTURA_ESTADOAsync(FACTURA_ESTADO obj) {
            this.buscarFACTURA_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarFACTURA_ESTADOAsync(FACTURA_ESTADO obj, object userState) {
            if ((this.buscarFACTURA_ESTADOOperationCompleted == null)) {
                this.buscarFACTURA_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarFACTURA_ESTADOOperationCompleted);
            }
            this.InvokeAsync("buscarFACTURA_ESTADO", new object[] {
                        obj}, this.buscarFACTURA_ESTADOOperationCompleted, userState);
        }
        
        private void OnbuscarFACTURA_ESTADOOperationCompleted(object arg) {
            if ((this.buscarFACTURA_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarFACTURA_ESTADOCompleted(this, new buscarFACTURA_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarFACTURA_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA_ESTADO[] listarFACTURA_ESTADO() {
            object[] results = this.Invoke("listarFACTURA_ESTADO", new object[0]);
            return ((FACTURA_ESTADO[])(results[0]));
        }
        
        /// <remarks/>
        public void listarFACTURA_ESTADOAsync() {
            this.listarFACTURA_ESTADOAsync(null);
        }
        
        /// <remarks/>
        public void listarFACTURA_ESTADOAsync(object userState) {
            if ((this.listarFACTURA_ESTADOOperationCompleted == null)) {
                this.listarFACTURA_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarFACTURA_ESTADOOperationCompleted);
            }
            this.InvokeAsync("listarFACTURA_ESTADO", new object[0], this.listarFACTURA_ESTADOOperationCompleted, userState);
        }
        
        private void OnlistarFACTURA_ESTADOOperationCompleted(object arg) {
            if ((this.listarFACTURA_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarFACTURA_ESTADOCompleted(this, new listarFACTURA_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarFACTURA_ESTADO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarFACTURA_ESTADO(FACTURA_ESTADO obj) {
            object[] results = this.Invoke("eliminarFACTURA_ESTADO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarFACTURA_ESTADOAsync(FACTURA_ESTADO obj) {
            this.eliminarFACTURA_ESTADOAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarFACTURA_ESTADOAsync(FACTURA_ESTADO obj, object userState) {
            if ((this.eliminarFACTURA_ESTADOOperationCompleted == null)) {
                this.eliminarFACTURA_ESTADOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarFACTURA_ESTADOOperationCompleted);
            }
            this.InvokeAsync("eliminarFACTURA_ESTADO", new object[] {
                        obj}, this.eliminarFACTURA_ESTADOOperationCompleted, userState);
        }
        
        private void OneliminarFACTURA_ESTADOOperationCompleted(object arg) {
            if ((this.eliminarFACTURA_ESTADOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarFACTURA_ESTADOCompleted(this, new eliminarFACTURA_ESTADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FACTURA_ESTADO {
        
        private int idField;
        
        private string eSTADOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearFACTURA_ESTADOCompletedEventHandler(object sender, crearFACTURA_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearFACTURA_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearFACTURA_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA_ESTADO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA_ESTADO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarFACTURA_ESTADOCompletedEventHandler(object sender, editarFACTURA_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarFACTURA_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarFACTURA_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroFACTURA_ESTADOCompletedEventHandler(object sender, buscarPrimeroFACTURA_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroFACTURA_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroFACTURA_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA_ESTADO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA_ESTADO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarFACTURA_ESTADOCompletedEventHandler(object sender, buscarFACTURA_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarFACTURA_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarFACTURA_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA_ESTADO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA_ESTADO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarFACTURA_ESTADOCompletedEventHandler(object sender, listarFACTURA_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarFACTURA_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarFACTURA_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA_ESTADO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA_ESTADO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarFACTURA_ESTADOCompletedEventHandler(object sender, eliminarFACTURA_ESTADOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarFACTURA_ESTADOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarFACTURA_ESTADOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591