//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosTARIFA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosTARIFASoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosTARIFA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearTARIFAOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarTARIFAOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroTARIFAOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarTARIFAOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarTARIFAOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTARIFAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosTARIFA() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosTARIFA_ServiciosTARIFA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearTARIFACompletedEventHandler crearTARIFACompleted;
        
        /// <remarks/>
        public event editarTARIFACompletedEventHandler editarTARIFACompleted;
        
        /// <remarks/>
        public event buscarPrimeroTARIFACompletedEventHandler buscarPrimeroTARIFACompleted;
        
        /// <remarks/>
        public event buscarTARIFACompletedEventHandler buscarTARIFACompleted;
        
        /// <remarks/>
        public event listarTARIFACompletedEventHandler listarTARIFACompleted;
        
        /// <remarks/>
        public event eliminarTARIFACompletedEventHandler eliminarTARIFACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearTARIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA crearTARIFA(TARIFA obj) {
            object[] results = this.Invoke("crearTARIFA", new object[] {
                        obj});
            return ((TARIFA)(results[0]));
        }
        
        /// <remarks/>
        public void crearTARIFAAsync(TARIFA obj) {
            this.crearTARIFAAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearTARIFAAsync(TARIFA obj, object userState) {
            if ((this.crearTARIFAOperationCompleted == null)) {
                this.crearTARIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearTARIFAOperationCompleted);
            }
            this.InvokeAsync("crearTARIFA", new object[] {
                        obj}, this.crearTARIFAOperationCompleted, userState);
        }
        
        private void OncrearTARIFAOperationCompleted(object arg) {
            if ((this.crearTARIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearTARIFACompleted(this, new crearTARIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarTARIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarTARIFA(TARIFA obj) {
            object[] results = this.Invoke("editarTARIFA", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarTARIFAAsync(TARIFA obj) {
            this.editarTARIFAAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarTARIFAAsync(TARIFA obj, object userState) {
            if ((this.editarTARIFAOperationCompleted == null)) {
                this.editarTARIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarTARIFAOperationCompleted);
            }
            this.InvokeAsync("editarTARIFA", new object[] {
                        obj}, this.editarTARIFAOperationCompleted, userState);
        }
        
        private void OneditarTARIFAOperationCompleted(object arg) {
            if ((this.editarTARIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarTARIFACompleted(this, new editarTARIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroTARIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA buscarPrimeroTARIFA(TARIFA obj) {
            object[] results = this.Invoke("buscarPrimeroTARIFA", new object[] {
                        obj});
            return ((TARIFA)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroTARIFAAsync(TARIFA obj) {
            this.buscarPrimeroTARIFAAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroTARIFAAsync(TARIFA obj, object userState) {
            if ((this.buscarPrimeroTARIFAOperationCompleted == null)) {
                this.buscarPrimeroTARIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroTARIFAOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroTARIFA", new object[] {
                        obj}, this.buscarPrimeroTARIFAOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroTARIFAOperationCompleted(object arg) {
            if ((this.buscarPrimeroTARIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroTARIFACompleted(this, new buscarPrimeroTARIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarTARIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA[] buscarTARIFA(TARIFA obj) {
            object[] results = this.Invoke("buscarTARIFA", new object[] {
                        obj});
            return ((TARIFA[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarTARIFAAsync(TARIFA obj) {
            this.buscarTARIFAAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarTARIFAAsync(TARIFA obj, object userState) {
            if ((this.buscarTARIFAOperationCompleted == null)) {
                this.buscarTARIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarTARIFAOperationCompleted);
            }
            this.InvokeAsync("buscarTARIFA", new object[] {
                        obj}, this.buscarTARIFAOperationCompleted, userState);
        }
        
        private void OnbuscarTARIFAOperationCompleted(object arg) {
            if ((this.buscarTARIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarTARIFACompleted(this, new buscarTARIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarTARIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA[] listarTARIFA() {
            object[] results = this.Invoke("listarTARIFA", new object[0]);
            return ((TARIFA[])(results[0]));
        }
        
        /// <remarks/>
        public void listarTARIFAAsync() {
            this.listarTARIFAAsync(null);
        }
        
        /// <remarks/>
        public void listarTARIFAAsync(object userState) {
            if ((this.listarTARIFAOperationCompleted == null)) {
                this.listarTARIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarTARIFAOperationCompleted);
            }
            this.InvokeAsync("listarTARIFA", new object[0], this.listarTARIFAOperationCompleted, userState);
        }
        
        private void OnlistarTARIFAOperationCompleted(object arg) {
            if ((this.listarTARIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarTARIFACompleted(this, new listarTARIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarTARIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarTARIFA(TARIFA obj) {
            object[] results = this.Invoke("eliminarTARIFA", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTARIFAAsync(TARIFA obj) {
            this.eliminarTARIFAAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarTARIFAAsync(TARIFA obj, object userState) {
            if ((this.eliminarTARIFAOperationCompleted == null)) {
                this.eliminarTARIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTARIFAOperationCompleted);
            }
            this.InvokeAsync("eliminarTARIFA", new object[] {
                        obj}, this.eliminarTARIFAOperationCompleted, userState);
        }
        
        private void OneliminarTARIFAOperationCompleted(object arg) {
            if ((this.eliminarTARIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTARIFACompleted(this, new eliminarTARIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TARIFA {
        
        private int idField;
        
        private int iD_VIGENCIAField;
        
        private int iD_TARIFA_CATEGORIAField;
        
        private string nOMBREField;
        
        private string eSTADOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_VIGENCIA {
            get {
                return this.iD_VIGENCIAField;
            }
            set {
                this.iD_VIGENCIAField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA_CATEGORIA {
            get {
                return this.iD_TARIFA_CATEGORIAField;
            }
            set {
                this.iD_TARIFA_CATEGORIAField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearTARIFACompletedEventHandler(object sender, crearTARIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearTARIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearTARIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarTARIFACompletedEventHandler(object sender, editarTARIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarTARIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarTARIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroTARIFACompletedEventHandler(object sender, buscarPrimeroTARIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroTARIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroTARIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarTARIFACompletedEventHandler(object sender, buscarTARIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarTARIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarTARIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarTARIFACompletedEventHandler(object sender, listarTARIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarTARIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarTARIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarTARIFACompletedEventHandler(object sender, eliminarTARIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTARIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTARIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591