//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosLIQUIDACION {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosLIQUIDACIONSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosLIQUIDACION : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearLIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearMultipleLIQUIDACION_1OperationCompleted;
        
        private System.Threading.SendOrPostCallback crearMultipleLIQUIDACION_2OperationCompleted;
        
        private System.Threading.SendOrPostCallback editarLIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroLIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarLIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarLIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarLIQUIDACIONOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosLIQUIDACION() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosLIQUIDACION_ServiciosLIQUIDACION;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearLIQUIDACIONCompletedEventHandler crearLIQUIDACIONCompleted;
        
        /// <remarks/>
        public event crearMultipleLIQUIDACION_1CompletedEventHandler crearMultipleLIQUIDACION_1Completed;
        
        /// <remarks/>
        public event crearMultipleLIQUIDACION_2CompletedEventHandler crearMultipleLIQUIDACION_2Completed;
        
        /// <remarks/>
        public event editarLIQUIDACIONCompletedEventHandler editarLIQUIDACIONCompleted;
        
        /// <remarks/>
        public event buscarPrimeroLIQUIDACIONCompletedEventHandler buscarPrimeroLIQUIDACIONCompleted;
        
        /// <remarks/>
        public event buscarLIQUIDACIONCompletedEventHandler buscarLIQUIDACIONCompleted;
        
        /// <remarks/>
        public event listarLIQUIDACIONCompletedEventHandler listarLIQUIDACIONCompleted;
        
        /// <remarks/>
        public event eliminarLIQUIDACIONCompletedEventHandler eliminarLIQUIDACIONCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearLIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LIQUIDACION crearLIQUIDACION(LIQUIDACION obj) {
            object[] results = this.Invoke("crearLIQUIDACION", new object[] {
                        obj});
            return ((LIQUIDACION)(results[0]));
        }
        
        /// <remarks/>
        public void crearLIQUIDACIONAsync(LIQUIDACION obj) {
            this.crearLIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearLIQUIDACIONAsync(LIQUIDACION obj, object userState) {
            if ((this.crearLIQUIDACIONOperationCompleted == null)) {
                this.crearLIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearLIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("crearLIQUIDACION", new object[] {
                        obj}, this.crearLIQUIDACIONOperationCompleted, userState);
        }
        
        private void OncrearLIQUIDACIONOperationCompleted(object arg) {
            if ((this.crearLIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearLIQUIDACIONCompleted(this, new crearLIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearMultipleLIQUIDACION_1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet crearMultipleLIQUIDACION_1(TARIFA tarifa, int id_cliente) {
            object[] results = this.Invoke("crearMultipleLIQUIDACION_1", new object[] {
                        tarifa,
                        id_cliente});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void crearMultipleLIQUIDACION_1Async(TARIFA tarifa, int id_cliente) {
            this.crearMultipleLIQUIDACION_1Async(tarifa, id_cliente, null);
        }
        
        /// <remarks/>
        public void crearMultipleLIQUIDACION_1Async(TARIFA tarifa, int id_cliente, object userState) {
            if ((this.crearMultipleLIQUIDACION_1OperationCompleted == null)) {
                this.crearMultipleLIQUIDACION_1OperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearMultipleLIQUIDACION_1OperationCompleted);
            }
            this.InvokeAsync("crearMultipleLIQUIDACION_1", new object[] {
                        tarifa,
                        id_cliente}, this.crearMultipleLIQUIDACION_1OperationCompleted, userState);
        }
        
        private void OncrearMultipleLIQUIDACION_1OperationCompleted(object arg) {
            if ((this.crearMultipleLIQUIDACION_1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearMultipleLIQUIDACION_1Completed(this, new crearMultipleLIQUIDACION_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearMultipleLIQUIDACION_2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LIQUIDACION crearMultipleLIQUIDACION_2(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente) {
            object[] results = this.Invoke("crearMultipleLIQUIDACION_2", new object[] {
                        liquidacion,
                        lstDetalles,
                        myCliente});
            return ((LIQUIDACION)(results[0]));
        }
        
        /// <remarks/>
        public void crearMultipleLIQUIDACION_2Async(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente) {
            this.crearMultipleLIQUIDACION_2Async(liquidacion, lstDetalles, myCliente, null);
        }
        
        /// <remarks/>
        public void crearMultipleLIQUIDACION_2Async(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente, object userState) {
            if ((this.crearMultipleLIQUIDACION_2OperationCompleted == null)) {
                this.crearMultipleLIQUIDACION_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearMultipleLIQUIDACION_2OperationCompleted);
            }
            this.InvokeAsync("crearMultipleLIQUIDACION_2", new object[] {
                        liquidacion,
                        lstDetalles,
                        myCliente}, this.crearMultipleLIQUIDACION_2OperationCompleted, userState);
        }
        
        private void OncrearMultipleLIQUIDACION_2OperationCompleted(object arg) {
            if ((this.crearMultipleLIQUIDACION_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearMultipleLIQUIDACION_2Completed(this, new crearMultipleLIQUIDACION_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarLIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarLIQUIDACION(LIQUIDACION obj) {
            object[] results = this.Invoke("editarLIQUIDACION", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarLIQUIDACIONAsync(LIQUIDACION obj) {
            this.editarLIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarLIQUIDACIONAsync(LIQUIDACION obj, object userState) {
            if ((this.editarLIQUIDACIONOperationCompleted == null)) {
                this.editarLIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarLIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("editarLIQUIDACION", new object[] {
                        obj}, this.editarLIQUIDACIONOperationCompleted, userState);
        }
        
        private void OneditarLIQUIDACIONOperationCompleted(object arg) {
            if ((this.editarLIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarLIQUIDACIONCompleted(this, new editarLIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroLIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LIQUIDACION buscarPrimeroLIQUIDACION(LIQUIDACION obj) {
            object[] results = this.Invoke("buscarPrimeroLIQUIDACION", new object[] {
                        obj});
            return ((LIQUIDACION)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroLIQUIDACIONAsync(LIQUIDACION obj) {
            this.buscarPrimeroLIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroLIQUIDACIONAsync(LIQUIDACION obj, object userState) {
            if ((this.buscarPrimeroLIQUIDACIONOperationCompleted == null)) {
                this.buscarPrimeroLIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroLIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroLIQUIDACION", new object[] {
                        obj}, this.buscarPrimeroLIQUIDACIONOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroLIQUIDACIONOperationCompleted(object arg) {
            if ((this.buscarPrimeroLIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroLIQUIDACIONCompleted(this, new buscarPrimeroLIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarLIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LIQUIDACION[] buscarLIQUIDACION(LIQUIDACION obj) {
            object[] results = this.Invoke("buscarLIQUIDACION", new object[] {
                        obj});
            return ((LIQUIDACION[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarLIQUIDACIONAsync(LIQUIDACION obj) {
            this.buscarLIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarLIQUIDACIONAsync(LIQUIDACION obj, object userState) {
            if ((this.buscarLIQUIDACIONOperationCompleted == null)) {
                this.buscarLIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarLIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("buscarLIQUIDACION", new object[] {
                        obj}, this.buscarLIQUIDACIONOperationCompleted, userState);
        }
        
        private void OnbuscarLIQUIDACIONOperationCompleted(object arg) {
            if ((this.buscarLIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarLIQUIDACIONCompleted(this, new buscarLIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarLIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LIQUIDACION[] listarLIQUIDACION() {
            object[] results = this.Invoke("listarLIQUIDACION", new object[0]);
            return ((LIQUIDACION[])(results[0]));
        }
        
        /// <remarks/>
        public void listarLIQUIDACIONAsync() {
            this.listarLIQUIDACIONAsync(null);
        }
        
        /// <remarks/>
        public void listarLIQUIDACIONAsync(object userState) {
            if ((this.listarLIQUIDACIONOperationCompleted == null)) {
                this.listarLIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarLIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("listarLIQUIDACION", new object[0], this.listarLIQUIDACIONOperationCompleted, userState);
        }
        
        private void OnlistarLIQUIDACIONOperationCompleted(object arg) {
            if ((this.listarLIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarLIQUIDACIONCompleted(this, new listarLIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarLIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarLIQUIDACION(LIQUIDACION obj) {
            object[] results = this.Invoke("eliminarLIQUIDACION", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarLIQUIDACIONAsync(LIQUIDACION obj) {
            this.eliminarLIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarLIQUIDACIONAsync(LIQUIDACION obj, object userState) {
            if ((this.eliminarLIQUIDACIONOperationCompleted == null)) {
                this.eliminarLIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarLIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("eliminarLIQUIDACION", new object[] {
                        obj}, this.eliminarLIQUIDACIONOperationCompleted, userState);
        }
        
        private void OneliminarLIQUIDACIONOperationCompleted(object arg) {
            if ((this.eliminarLIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarLIQUIDACIONCompleted(this, new eliminarLIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LIQUIDACION {
        
        private int idField;
        
        private int iD_CLIENTEField;
        
        private int iD_TIPO_LIQUIDACIONField;
        
        private System.DateTime fECHA_LIQUIDACIONField;
        
        private float tOTALField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_CLIENTE {
            get {
                return this.iD_CLIENTEField;
            }
            set {
                this.iD_CLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TIPO_LIQUIDACION {
            get {
                return this.iD_TIPO_LIQUIDACIONField;
            }
            set {
                this.iD_TIPO_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_LIQUIDACION {
            get {
                return this.fECHA_LIQUIDACIONField;
            }
            set {
                this.fECHA_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public float TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VIEW_CLIENTE {
        
        private int idField;
        
        private string tIPO_DOCUMENTOField;
        
        private string iDENTIFICACIONField;
        
        private string nOMBRESField;
        
        private string aPELLIDOSField;
        
        private string dIRECCIONField;
        
        private string cIUDADField;
        
        private string dEPARTAMENTOField;
        
        private string gENEROField;
        
        private string tELEFONOField;
        
        private string cELULARField;
        
        private string cORREOField;
        
        private string fECHA_NACIMIENTOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO_DOCUMENTO {
            get {
                return this.tIPO_DOCUMENTOField;
            }
            set {
                this.tIPO_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string IDENTIFICACION {
            get {
                return this.iDENTIFICACIONField;
            }
            set {
                this.iDENTIFICACIONField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <remarks/>
        public string APELLIDOS {
            get {
                return this.aPELLIDOSField;
            }
            set {
                this.aPELLIDOSField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        public string CIUDAD {
            get {
                return this.cIUDADField;
            }
            set {
                this.cIUDADField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTAMENTO {
            get {
                return this.dEPARTAMENTOField;
            }
            set {
                this.dEPARTAMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string GENERO {
            get {
                return this.gENEROField;
            }
            set {
                this.gENEROField = value;
            }
        }
        
        /// <remarks/>
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <remarks/>
        public string CELULAR {
            get {
                return this.cELULARField;
            }
            set {
                this.cELULARField = value;
            }
        }
        
        /// <remarks/>
        public string CORREO {
            get {
                return this.cORREOField;
            }
            set {
                this.cORREOField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_NACIMIENTO {
            get {
                return this.fECHA_NACIMIENTOField;
            }
            set {
                this.fECHA_NACIMIENTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LIQUIDACION_DETALLE {
        
        private int idField;
        
        private int iD_LIQUIDACIONField;
        
        private int iD_TARIFA_DETALLEField;
        
        private float vALOR_CONCEPTOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_LIQUIDACION {
            get {
                return this.iD_LIQUIDACIONField;
            }
            set {
                this.iD_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA_DETALLE {
            get {
                return this.iD_TARIFA_DETALLEField;
            }
            set {
                this.iD_TARIFA_DETALLEField = value;
            }
        }
        
        /// <remarks/>
        public float VALOR_CONCEPTO {
            get {
                return this.vALOR_CONCEPTOField;
            }
            set {
                this.vALOR_CONCEPTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TARIFA {
        
        private int idField;
        
        private int iD_VIGENCIAField;
        
        private int iD_TARIFA_CATEGORIAField;
        
        private string nOMBREField;
        
        private string eSTADOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_VIGENCIA {
            get {
                return this.iD_VIGENCIAField;
            }
            set {
                this.iD_VIGENCIAField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA_CATEGORIA {
            get {
                return this.iD_TARIFA_CATEGORIAField;
            }
            set {
                this.iD_TARIFA_CATEGORIAField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearLIQUIDACIONCompletedEventHandler(object sender, crearLIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearLIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearLIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LIQUIDACION Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LIQUIDACION)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearMultipleLIQUIDACION_1CompletedEventHandler(object sender, crearMultipleLIQUIDACION_1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearMultipleLIQUIDACION_1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearMultipleLIQUIDACION_1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearMultipleLIQUIDACION_2CompletedEventHandler(object sender, crearMultipleLIQUIDACION_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearMultipleLIQUIDACION_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearMultipleLIQUIDACION_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LIQUIDACION Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LIQUIDACION)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarLIQUIDACIONCompletedEventHandler(object sender, editarLIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarLIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarLIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroLIQUIDACIONCompletedEventHandler(object sender, buscarPrimeroLIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroLIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroLIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LIQUIDACION Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LIQUIDACION)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarLIQUIDACIONCompletedEventHandler(object sender, buscarLIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarLIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarLIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LIQUIDACION[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LIQUIDACION[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarLIQUIDACIONCompletedEventHandler(object sender, listarLIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarLIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarLIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LIQUIDACION[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LIQUIDACION[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarLIQUIDACIONCompletedEventHandler(object sender, eliminarLIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarLIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarLIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591