//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosACUERDO_PAGO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosACUERDO_PAGOSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosACUERDO_PAGO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearACUERDO_PAGOOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarACUERDO_PAGOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroACUERDO_PAGOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarACUERDO_PAGOOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarACUERDO_PAGOOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarACUERDO_PAGOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosACUERDO_PAGO() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosACUERDO_PAGO_ServiciosACUERDO_PAGO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearACUERDO_PAGOCompletedEventHandler crearACUERDO_PAGOCompleted;
        
        /// <remarks/>
        public event editarACUERDO_PAGOCompletedEventHandler editarACUERDO_PAGOCompleted;
        
        /// <remarks/>
        public event buscarPrimeroACUERDO_PAGOCompletedEventHandler buscarPrimeroACUERDO_PAGOCompleted;
        
        /// <remarks/>
        public event buscarACUERDO_PAGOCompletedEventHandler buscarACUERDO_PAGOCompleted;
        
        /// <remarks/>
        public event listarACUERDO_PAGOCompletedEventHandler listarACUERDO_PAGOCompleted;
        
        /// <remarks/>
        public event eliminarACUERDO_PAGOCompletedEventHandler eliminarACUERDO_PAGOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearACUERDO_PAGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_PAGO crearACUERDO_PAGO(ACUERDO_PAGO obj) {
            object[] results = this.Invoke("crearACUERDO_PAGO", new object[] {
                        obj});
            return ((ACUERDO_PAGO)(results[0]));
        }
        
        /// <remarks/>
        public void crearACUERDO_PAGOAsync(ACUERDO_PAGO obj) {
            this.crearACUERDO_PAGOAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearACUERDO_PAGOAsync(ACUERDO_PAGO obj, object userState) {
            if ((this.crearACUERDO_PAGOOperationCompleted == null)) {
                this.crearACUERDO_PAGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearACUERDO_PAGOOperationCompleted);
            }
            this.InvokeAsync("crearACUERDO_PAGO", new object[] {
                        obj}, this.crearACUERDO_PAGOOperationCompleted, userState);
        }
        
        private void OncrearACUERDO_PAGOOperationCompleted(object arg) {
            if ((this.crearACUERDO_PAGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearACUERDO_PAGOCompleted(this, new crearACUERDO_PAGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarACUERDO_PAGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarACUERDO_PAGO(ACUERDO_PAGO obj) {
            object[] results = this.Invoke("editarACUERDO_PAGO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarACUERDO_PAGOAsync(ACUERDO_PAGO obj) {
            this.editarACUERDO_PAGOAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarACUERDO_PAGOAsync(ACUERDO_PAGO obj, object userState) {
            if ((this.editarACUERDO_PAGOOperationCompleted == null)) {
                this.editarACUERDO_PAGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarACUERDO_PAGOOperationCompleted);
            }
            this.InvokeAsync("editarACUERDO_PAGO", new object[] {
                        obj}, this.editarACUERDO_PAGOOperationCompleted, userState);
        }
        
        private void OneditarACUERDO_PAGOOperationCompleted(object arg) {
            if ((this.editarACUERDO_PAGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarACUERDO_PAGOCompleted(this, new editarACUERDO_PAGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroACUERDO_PAGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_PAGO buscarPrimeroACUERDO_PAGO(ACUERDO_PAGO obj) {
            object[] results = this.Invoke("buscarPrimeroACUERDO_PAGO", new object[] {
                        obj});
            return ((ACUERDO_PAGO)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroACUERDO_PAGOAsync(ACUERDO_PAGO obj) {
            this.buscarPrimeroACUERDO_PAGOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroACUERDO_PAGOAsync(ACUERDO_PAGO obj, object userState) {
            if ((this.buscarPrimeroACUERDO_PAGOOperationCompleted == null)) {
                this.buscarPrimeroACUERDO_PAGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroACUERDO_PAGOOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroACUERDO_PAGO", new object[] {
                        obj}, this.buscarPrimeroACUERDO_PAGOOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroACUERDO_PAGOOperationCompleted(object arg) {
            if ((this.buscarPrimeroACUERDO_PAGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroACUERDO_PAGOCompleted(this, new buscarPrimeroACUERDO_PAGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarACUERDO_PAGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_PAGO[] buscarACUERDO_PAGO(ACUERDO_PAGO obj) {
            object[] results = this.Invoke("buscarACUERDO_PAGO", new object[] {
                        obj});
            return ((ACUERDO_PAGO[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarACUERDO_PAGOAsync(ACUERDO_PAGO obj) {
            this.buscarACUERDO_PAGOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarACUERDO_PAGOAsync(ACUERDO_PAGO obj, object userState) {
            if ((this.buscarACUERDO_PAGOOperationCompleted == null)) {
                this.buscarACUERDO_PAGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarACUERDO_PAGOOperationCompleted);
            }
            this.InvokeAsync("buscarACUERDO_PAGO", new object[] {
                        obj}, this.buscarACUERDO_PAGOOperationCompleted, userState);
        }
        
        private void OnbuscarACUERDO_PAGOOperationCompleted(object arg) {
            if ((this.buscarACUERDO_PAGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarACUERDO_PAGOCompleted(this, new buscarACUERDO_PAGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarACUERDO_PAGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACUERDO_PAGO[] listarACUERDO_PAGO() {
            object[] results = this.Invoke("listarACUERDO_PAGO", new object[0]);
            return ((ACUERDO_PAGO[])(results[0]));
        }
        
        /// <remarks/>
        public void listarACUERDO_PAGOAsync() {
            this.listarACUERDO_PAGOAsync(null);
        }
        
        /// <remarks/>
        public void listarACUERDO_PAGOAsync(object userState) {
            if ((this.listarACUERDO_PAGOOperationCompleted == null)) {
                this.listarACUERDO_PAGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarACUERDO_PAGOOperationCompleted);
            }
            this.InvokeAsync("listarACUERDO_PAGO", new object[0], this.listarACUERDO_PAGOOperationCompleted, userState);
        }
        
        private void OnlistarACUERDO_PAGOOperationCompleted(object arg) {
            if ((this.listarACUERDO_PAGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarACUERDO_PAGOCompleted(this, new listarACUERDO_PAGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarACUERDO_PAGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarACUERDO_PAGO(ACUERDO_PAGO obj) {
            object[] results = this.Invoke("eliminarACUERDO_PAGO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarACUERDO_PAGOAsync(ACUERDO_PAGO obj) {
            this.eliminarACUERDO_PAGOAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarACUERDO_PAGOAsync(ACUERDO_PAGO obj, object userState) {
            if ((this.eliminarACUERDO_PAGOOperationCompleted == null)) {
                this.eliminarACUERDO_PAGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarACUERDO_PAGOOperationCompleted);
            }
            this.InvokeAsync("eliminarACUERDO_PAGO", new object[] {
                        obj}, this.eliminarACUERDO_PAGOOperationCompleted, userState);
        }
        
        private void OneliminarACUERDO_PAGOOperationCompleted(object arg) {
            if ((this.eliminarACUERDO_PAGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarACUERDO_PAGOCompleted(this, new eliminarACUERDO_PAGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ACUERDO_PAGO {
        
        private int idField;
        
        private int iD_LIQUIDACIONField;
        
        private int iD_ACUERDO_ESTADOField;
        
        private string nUMERO_ACUERDOField;
        
        private System.DateTime fECHA_ACUERDOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_LIQUIDACION {
            get {
                return this.iD_LIQUIDACIONField;
            }
            set {
                this.iD_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public int ID_ACUERDO_ESTADO {
            get {
                return this.iD_ACUERDO_ESTADOField;
            }
            set {
                this.iD_ACUERDO_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_ACUERDO {
            get {
                return this.nUMERO_ACUERDOField;
            }
            set {
                this.nUMERO_ACUERDOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_ACUERDO {
            get {
                return this.fECHA_ACUERDOField;
            }
            set {
                this.fECHA_ACUERDOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearACUERDO_PAGOCompletedEventHandler(object sender, crearACUERDO_PAGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearACUERDO_PAGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearACUERDO_PAGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_PAGO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_PAGO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarACUERDO_PAGOCompletedEventHandler(object sender, editarACUERDO_PAGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarACUERDO_PAGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarACUERDO_PAGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroACUERDO_PAGOCompletedEventHandler(object sender, buscarPrimeroACUERDO_PAGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroACUERDO_PAGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroACUERDO_PAGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_PAGO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_PAGO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarACUERDO_PAGOCompletedEventHandler(object sender, buscarACUERDO_PAGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarACUERDO_PAGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarACUERDO_PAGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_PAGO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_PAGO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarACUERDO_PAGOCompletedEventHandler(object sender, listarACUERDO_PAGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarACUERDO_PAGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarACUERDO_PAGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACUERDO_PAGO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACUERDO_PAGO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarACUERDO_PAGOCompletedEventHandler(object sender, eliminarACUERDO_PAGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarACUERDO_PAGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarACUERDO_PAGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591