//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosTARIFA_DETALLE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosTARIFA_DETALLESoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosTARIFA_DETALLE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearTARIFA_DETALLEOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarTARIFA_DETALLEOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroTARIFA_DETALLEOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarTARIFA_DETALLEOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarTARIFA_DETALLEOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTARIFA_DETALLEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosTARIFA_DETALLE() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosTARIFA_DETALLE_ServiciosTARIFA_DETALLE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearTARIFA_DETALLECompletedEventHandler crearTARIFA_DETALLECompleted;
        
        /// <remarks/>
        public event editarTARIFA_DETALLECompletedEventHandler editarTARIFA_DETALLECompleted;
        
        /// <remarks/>
        public event buscarPrimeroTARIFA_DETALLECompletedEventHandler buscarPrimeroTARIFA_DETALLECompleted;
        
        /// <remarks/>
        public event buscarTARIFA_DETALLECompletedEventHandler buscarTARIFA_DETALLECompleted;
        
        /// <remarks/>
        public event listarTARIFA_DETALLECompletedEventHandler listarTARIFA_DETALLECompleted;
        
        /// <remarks/>
        public event eliminarTARIFA_DETALLECompletedEventHandler eliminarTARIFA_DETALLECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearTARIFA_DETALLE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA_DETALLE crearTARIFA_DETALLE(TARIFA_DETALLE obj) {
            object[] results = this.Invoke("crearTARIFA_DETALLE", new object[] {
                        obj});
            return ((TARIFA_DETALLE)(results[0]));
        }
        
        /// <remarks/>
        public void crearTARIFA_DETALLEAsync(TARIFA_DETALLE obj) {
            this.crearTARIFA_DETALLEAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearTARIFA_DETALLEAsync(TARIFA_DETALLE obj, object userState) {
            if ((this.crearTARIFA_DETALLEOperationCompleted == null)) {
                this.crearTARIFA_DETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearTARIFA_DETALLEOperationCompleted);
            }
            this.InvokeAsync("crearTARIFA_DETALLE", new object[] {
                        obj}, this.crearTARIFA_DETALLEOperationCompleted, userState);
        }
        
        private void OncrearTARIFA_DETALLEOperationCompleted(object arg) {
            if ((this.crearTARIFA_DETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearTARIFA_DETALLECompleted(this, new crearTARIFA_DETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarTARIFA_DETALLE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarTARIFA_DETALLE(TARIFA_DETALLE obj) {
            object[] results = this.Invoke("editarTARIFA_DETALLE", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarTARIFA_DETALLEAsync(TARIFA_DETALLE obj) {
            this.editarTARIFA_DETALLEAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarTARIFA_DETALLEAsync(TARIFA_DETALLE obj, object userState) {
            if ((this.editarTARIFA_DETALLEOperationCompleted == null)) {
                this.editarTARIFA_DETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarTARIFA_DETALLEOperationCompleted);
            }
            this.InvokeAsync("editarTARIFA_DETALLE", new object[] {
                        obj}, this.editarTARIFA_DETALLEOperationCompleted, userState);
        }
        
        private void OneditarTARIFA_DETALLEOperationCompleted(object arg) {
            if ((this.editarTARIFA_DETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarTARIFA_DETALLECompleted(this, new editarTARIFA_DETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroTARIFA_DETALLE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA_DETALLE buscarPrimeroTARIFA_DETALLE(TARIFA_DETALLE obj) {
            object[] results = this.Invoke("buscarPrimeroTARIFA_DETALLE", new object[] {
                        obj});
            return ((TARIFA_DETALLE)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroTARIFA_DETALLEAsync(TARIFA_DETALLE obj) {
            this.buscarPrimeroTARIFA_DETALLEAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroTARIFA_DETALLEAsync(TARIFA_DETALLE obj, object userState) {
            if ((this.buscarPrimeroTARIFA_DETALLEOperationCompleted == null)) {
                this.buscarPrimeroTARIFA_DETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroTARIFA_DETALLEOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroTARIFA_DETALLE", new object[] {
                        obj}, this.buscarPrimeroTARIFA_DETALLEOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroTARIFA_DETALLEOperationCompleted(object arg) {
            if ((this.buscarPrimeroTARIFA_DETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroTARIFA_DETALLECompleted(this, new buscarPrimeroTARIFA_DETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarTARIFA_DETALLE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA_DETALLE[] buscarTARIFA_DETALLE(TARIFA_DETALLE obj) {
            object[] results = this.Invoke("buscarTARIFA_DETALLE", new object[] {
                        obj});
            return ((TARIFA_DETALLE[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarTARIFA_DETALLEAsync(TARIFA_DETALLE obj) {
            this.buscarTARIFA_DETALLEAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarTARIFA_DETALLEAsync(TARIFA_DETALLE obj, object userState) {
            if ((this.buscarTARIFA_DETALLEOperationCompleted == null)) {
                this.buscarTARIFA_DETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarTARIFA_DETALLEOperationCompleted);
            }
            this.InvokeAsync("buscarTARIFA_DETALLE", new object[] {
                        obj}, this.buscarTARIFA_DETALLEOperationCompleted, userState);
        }
        
        private void OnbuscarTARIFA_DETALLEOperationCompleted(object arg) {
            if ((this.buscarTARIFA_DETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarTARIFA_DETALLECompleted(this, new buscarTARIFA_DETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarTARIFA_DETALLE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TARIFA_DETALLE[] listarTARIFA_DETALLE() {
            object[] results = this.Invoke("listarTARIFA_DETALLE", new object[0]);
            return ((TARIFA_DETALLE[])(results[0]));
        }
        
        /// <remarks/>
        public void listarTARIFA_DETALLEAsync() {
            this.listarTARIFA_DETALLEAsync(null);
        }
        
        /// <remarks/>
        public void listarTARIFA_DETALLEAsync(object userState) {
            if ((this.listarTARIFA_DETALLEOperationCompleted == null)) {
                this.listarTARIFA_DETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarTARIFA_DETALLEOperationCompleted);
            }
            this.InvokeAsync("listarTARIFA_DETALLE", new object[0], this.listarTARIFA_DETALLEOperationCompleted, userState);
        }
        
        private void OnlistarTARIFA_DETALLEOperationCompleted(object arg) {
            if ((this.listarTARIFA_DETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarTARIFA_DETALLECompleted(this, new listarTARIFA_DETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarTARIFA_DETALLE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarTARIFA_DETALLE(TARIFA_DETALLE obj) {
            object[] results = this.Invoke("eliminarTARIFA_DETALLE", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTARIFA_DETALLEAsync(TARIFA_DETALLE obj) {
            this.eliminarTARIFA_DETALLEAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarTARIFA_DETALLEAsync(TARIFA_DETALLE obj, object userState) {
            if ((this.eliminarTARIFA_DETALLEOperationCompleted == null)) {
                this.eliminarTARIFA_DETALLEOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTARIFA_DETALLEOperationCompleted);
            }
            this.InvokeAsync("eliminarTARIFA_DETALLE", new object[] {
                        obj}, this.eliminarTARIFA_DETALLEOperationCompleted, userState);
        }
        
        private void OneliminarTARIFA_DETALLEOperationCompleted(object arg) {
            if ((this.eliminarTARIFA_DETALLECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTARIFA_DETALLECompleted(this, new eliminarTARIFA_DETALLECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TARIFA_DETALLE {
        
        private int idField;
        
        private int iD_TARIFAField;
        
        private int iD_TARIFA_CONCEPTOField;
        
        private string tERCEROField;
        
        private string dESCONTABLEField;
        
        private string fORMULAField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA {
            get {
                return this.iD_TARIFAField;
            }
            set {
                this.iD_TARIFAField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA_CONCEPTO {
            get {
                return this.iD_TARIFA_CONCEPTOField;
            }
            set {
                this.iD_TARIFA_CONCEPTOField = value;
            }
        }
        
        /// <remarks/>
        public string TERCERO {
            get {
                return this.tERCEROField;
            }
            set {
                this.tERCEROField = value;
            }
        }
        
        /// <remarks/>
        public string DESCONTABLE {
            get {
                return this.dESCONTABLEField;
            }
            set {
                this.dESCONTABLEField = value;
            }
        }
        
        /// <remarks/>
        public string FORMULA {
            get {
                return this.fORMULAField;
            }
            set {
                this.fORMULAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearTARIFA_DETALLECompletedEventHandler(object sender, crearTARIFA_DETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearTARIFA_DETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearTARIFA_DETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA_DETALLE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA_DETALLE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarTARIFA_DETALLECompletedEventHandler(object sender, editarTARIFA_DETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarTARIFA_DETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarTARIFA_DETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroTARIFA_DETALLECompletedEventHandler(object sender, buscarPrimeroTARIFA_DETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroTARIFA_DETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroTARIFA_DETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA_DETALLE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA_DETALLE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarTARIFA_DETALLECompletedEventHandler(object sender, buscarTARIFA_DETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarTARIFA_DETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarTARIFA_DETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA_DETALLE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA_DETALLE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarTARIFA_DETALLECompletedEventHandler(object sender, listarTARIFA_DETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarTARIFA_DETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarTARIFA_DETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TARIFA_DETALLE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TARIFA_DETALLE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarTARIFA_DETALLECompletedEventHandler(object sender, eliminarTARIFA_DETALLECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTARIFA_DETALLECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTARIFA_DETALLECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591