//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosPagos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosPagosSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosPagos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPaginacionPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPaginacionPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarBusquedaPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarPagosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosPagos() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosPagos_ServiciosPagos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearPagosCompletedEventHandler crearPagosCompleted;
        
        /// <remarks/>
        public event editarPagosCompletedEventHandler editarPagosCompleted;
        
        /// <remarks/>
        public event buscarPrimeroPagosCompletedEventHandler buscarPrimeroPagosCompleted;
        
        /// <remarks/>
        public event buscarPagosCompletedEventHandler buscarPagosCompleted;
        
        /// <remarks/>
        public event buscarPaginacionPagosCompletedEventHandler buscarPaginacionPagosCompleted;
        
        /// <remarks/>
        public event listarPagosCompletedEventHandler listarPagosCompleted;
        
        /// <remarks/>
        public event listarPaginacionPagosCompletedEventHandler listarPaginacionPagosCompleted;
        
        /// <remarks/>
        public event contarBusquedaPagosCompletedEventHandler contarBusquedaPagosCompleted;
        
        /// <remarks/>
        public event eliminarPagosCompletedEventHandler eliminarPagosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos crearPagos(Pagos obj) {
            object[] results = this.Invoke("crearPagos", new object[] {
                        obj});
            return ((Pagos)(results[0]));
        }
        
        /// <remarks/>
        public void crearPagosAsync(Pagos obj) {
            this.crearPagosAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearPagosAsync(Pagos obj, object userState) {
            if ((this.crearPagosOperationCompleted == null)) {
                this.crearPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearPagosOperationCompleted);
            }
            this.InvokeAsync("crearPagos", new object[] {
                        obj}, this.crearPagosOperationCompleted, userState);
        }
        
        private void OncrearPagosOperationCompleted(object arg) {
            if ((this.crearPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearPagosCompleted(this, new crearPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarPagos(Pagos obj) {
            object[] results = this.Invoke("editarPagos", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarPagosAsync(Pagos obj) {
            this.editarPagosAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarPagosAsync(Pagos obj, object userState) {
            if ((this.editarPagosOperationCompleted == null)) {
                this.editarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarPagosOperationCompleted);
            }
            this.InvokeAsync("editarPagos", new object[] {
                        obj}, this.editarPagosOperationCompleted, userState);
        }
        
        private void OneditarPagosOperationCompleted(object arg) {
            if ((this.editarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarPagosCompleted(this, new editarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos buscarPrimeroPagos(Pagos obj) {
            object[] results = this.Invoke("buscarPrimeroPagos", new object[] {
                        obj});
            return ((Pagos)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroPagosAsync(Pagos obj) {
            this.buscarPrimeroPagosAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroPagosAsync(Pagos obj, object userState) {
            if ((this.buscarPrimeroPagosOperationCompleted == null)) {
                this.buscarPrimeroPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroPagosOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroPagos", new object[] {
                        obj}, this.buscarPrimeroPagosOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroPagosOperationCompleted(object arg) {
            if ((this.buscarPrimeroPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroPagosCompleted(this, new buscarPrimeroPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos[] buscarPagos(Pagos obj) {
            object[] results = this.Invoke("buscarPagos", new object[] {
                        obj});
            return ((Pagos[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPagosAsync(Pagos obj) {
            this.buscarPagosAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPagosAsync(Pagos obj, object userState) {
            if ((this.buscarPagosOperationCompleted == null)) {
                this.buscarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPagosOperationCompleted);
            }
            this.InvokeAsync("buscarPagos", new object[] {
                        obj}, this.buscarPagosOperationCompleted, userState);
        }
        
        private void OnbuscarPagosOperationCompleted(object arg) {
            if ((this.buscarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPagosCompleted(this, new buscarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaginacionPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos[] buscarPaginacionPagos(Pagos obj, int pag, int numReg) {
            object[] results = this.Invoke("buscarPaginacionPagos", new object[] {
                        obj,
                        pag,
                        numReg});
            return ((Pagos[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaginacionPagosAsync(Pagos obj, int pag, int numReg) {
            this.buscarPaginacionPagosAsync(obj, pag, numReg, null);
        }
        
        /// <remarks/>
        public void buscarPaginacionPagosAsync(Pagos obj, int pag, int numReg, object userState) {
            if ((this.buscarPaginacionPagosOperationCompleted == null)) {
                this.buscarPaginacionPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaginacionPagosOperationCompleted);
            }
            this.InvokeAsync("buscarPaginacionPagos", new object[] {
                        obj,
                        pag,
                        numReg}, this.buscarPaginacionPagosOperationCompleted, userState);
        }
        
        private void OnbuscarPaginacionPagosOperationCompleted(object arg) {
            if ((this.buscarPaginacionPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaginacionPagosCompleted(this, new buscarPaginacionPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos[] listarPagos() {
            object[] results = this.Invoke("listarPagos", new object[0]);
            return ((Pagos[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPagosAsync() {
            this.listarPagosAsync(null);
        }
        
        /// <remarks/>
        public void listarPagosAsync(object userState) {
            if ((this.listarPagosOperationCompleted == null)) {
                this.listarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPagosOperationCompleted);
            }
            this.InvokeAsync("listarPagos", new object[0], this.listarPagosOperationCompleted, userState);
        }
        
        private void OnlistarPagosOperationCompleted(object arg) {
            if ((this.listarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPagosCompleted(this, new listarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarPaginacionPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos[] listarPaginacionPagos(int pag, int numReg) {
            object[] results = this.Invoke("listarPaginacionPagos", new object[] {
                        pag,
                        numReg});
            return ((Pagos[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPaginacionPagosAsync(int pag, int numReg) {
            this.listarPaginacionPagosAsync(pag, numReg, null);
        }
        
        /// <remarks/>
        public void listarPaginacionPagosAsync(int pag, int numReg, object userState) {
            if ((this.listarPaginacionPagosOperationCompleted == null)) {
                this.listarPaginacionPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPaginacionPagosOperationCompleted);
            }
            this.InvokeAsync("listarPaginacionPagos", new object[] {
                        pag,
                        numReg}, this.listarPaginacionPagosOperationCompleted, userState);
        }
        
        private void OnlistarPaginacionPagosOperationCompleted(object arg) {
            if ((this.listarPaginacionPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPaginacionPagosCompleted(this, new listarPaginacionPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarBusquedaPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int contarBusquedaPagos(Pagos obj) {
            object[] results = this.Invoke("contarBusquedaPagos", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void contarBusquedaPagosAsync(Pagos obj) {
            this.contarBusquedaPagosAsync(obj, null);
        }
        
        /// <remarks/>
        public void contarBusquedaPagosAsync(Pagos obj, object userState) {
            if ((this.contarBusquedaPagosOperationCompleted == null)) {
                this.contarBusquedaPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarBusquedaPagosOperationCompleted);
            }
            this.InvokeAsync("contarBusquedaPagos", new object[] {
                        obj}, this.contarBusquedaPagosOperationCompleted, userState);
        }
        
        private void OncontarBusquedaPagosOperationCompleted(object arg) {
            if ((this.contarBusquedaPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarBusquedaPagosCompleted(this, new contarBusquedaPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarPagos(Pagos obj) {
            object[] results = this.Invoke("eliminarPagos", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarPagosAsync(Pagos obj) {
            this.eliminarPagosAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarPagosAsync(Pagos obj, object userState) {
            if ((this.eliminarPagosOperationCompleted == null)) {
                this.eliminarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarPagosOperationCompleted);
            }
            this.InvokeAsync("eliminarPagos", new object[] {
                        obj}, this.eliminarPagosOperationCompleted, userState);
        }
        
        private void OneliminarPagosOperationCompleted(object arg) {
            if ((this.eliminarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarPagosCompleted(this, new eliminarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pagos {
        
        private int idField;
        
        private int iD_RECIBOField;
        
        private int iD_FORMAPAGOField;
        
        private double vALORField;
        
        private System.DateTime fECHA_PAGOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_RECIBO {
            get {
                return this.iD_RECIBOField;
            }
            set {
                this.iD_RECIBOField = value;
            }
        }
        
        /// <remarks/>
        public int ID_FORMAPAGO {
            get {
                return this.iD_FORMAPAGOField;
            }
            set {
                this.iD_FORMAPAGOField = value;
            }
        }
        
        /// <remarks/>
        public double VALOR {
            get {
                return this.vALORField;
            }
            set {
                this.vALORField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_PAGO {
            get {
                return this.fECHA_PAGOField;
            }
            set {
                this.fECHA_PAGOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearPagosCompletedEventHandler(object sender, crearPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarPagosCompletedEventHandler(object sender, editarPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroPagosCompletedEventHandler(object sender, buscarPrimeroPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPagosCompletedEventHandler(object sender, buscarPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPaginacionPagosCompletedEventHandler(object sender, buscarPaginacionPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaginacionPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaginacionPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarPagosCompletedEventHandler(object sender, listarPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarPaginacionPagosCompletedEventHandler(object sender, listarPaginacionPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPaginacionPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPaginacionPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void contarBusquedaPagosCompletedEventHandler(object sender, contarBusquedaPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarBusquedaPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarBusquedaPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarPagosCompletedEventHandler(object sender, eliminarPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591