//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosTIPO_LIQUIDACION {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosTIPO_LIQUIDACIONSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosTIPO_LIQUIDACION : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearTIPO_LIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarTIPO_LIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroTIPO_LIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarTIPO_LIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarTIPO_LIQUIDACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTIPO_LIQUIDACIONOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosTIPO_LIQUIDACION() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosTIPO_LIQUIDACION_ServiciosTIPO_LIQUIDACION;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearTIPO_LIQUIDACIONCompletedEventHandler crearTIPO_LIQUIDACIONCompleted;
        
        /// <remarks/>
        public event editarTIPO_LIQUIDACIONCompletedEventHandler editarTIPO_LIQUIDACIONCompleted;
        
        /// <remarks/>
        public event buscarPrimeroTIPO_LIQUIDACIONCompletedEventHandler buscarPrimeroTIPO_LIQUIDACIONCompleted;
        
        /// <remarks/>
        public event buscarTIPO_LIQUIDACIONCompletedEventHandler buscarTIPO_LIQUIDACIONCompleted;
        
        /// <remarks/>
        public event listarTIPO_LIQUIDACIONCompletedEventHandler listarTIPO_LIQUIDACIONCompleted;
        
        /// <remarks/>
        public event eliminarTIPO_LIQUIDACIONCompletedEventHandler eliminarTIPO_LIQUIDACIONCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearTIPO_LIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_LIQUIDACION crearTIPO_LIQUIDACION(TIPO_LIQUIDACION obj) {
            object[] results = this.Invoke("crearTIPO_LIQUIDACION", new object[] {
                        obj});
            return ((TIPO_LIQUIDACION)(results[0]));
        }
        
        /// <remarks/>
        public void crearTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj) {
            this.crearTIPO_LIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj, object userState) {
            if ((this.crearTIPO_LIQUIDACIONOperationCompleted == null)) {
                this.crearTIPO_LIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearTIPO_LIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("crearTIPO_LIQUIDACION", new object[] {
                        obj}, this.crearTIPO_LIQUIDACIONOperationCompleted, userState);
        }
        
        private void OncrearTIPO_LIQUIDACIONOperationCompleted(object arg) {
            if ((this.crearTIPO_LIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearTIPO_LIQUIDACIONCompleted(this, new crearTIPO_LIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarTIPO_LIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarTIPO_LIQUIDACION(TIPO_LIQUIDACION obj) {
            object[] results = this.Invoke("editarTIPO_LIQUIDACION", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj) {
            this.editarTIPO_LIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj, object userState) {
            if ((this.editarTIPO_LIQUIDACIONOperationCompleted == null)) {
                this.editarTIPO_LIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarTIPO_LIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("editarTIPO_LIQUIDACION", new object[] {
                        obj}, this.editarTIPO_LIQUIDACIONOperationCompleted, userState);
        }
        
        private void OneditarTIPO_LIQUIDACIONOperationCompleted(object arg) {
            if ((this.editarTIPO_LIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarTIPO_LIQUIDACIONCompleted(this, new editarTIPO_LIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroTIPO_LIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_LIQUIDACION buscarPrimeroTIPO_LIQUIDACION(TIPO_LIQUIDACION obj) {
            object[] results = this.Invoke("buscarPrimeroTIPO_LIQUIDACION", new object[] {
                        obj});
            return ((TIPO_LIQUIDACION)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj) {
            this.buscarPrimeroTIPO_LIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj, object userState) {
            if ((this.buscarPrimeroTIPO_LIQUIDACIONOperationCompleted == null)) {
                this.buscarPrimeroTIPO_LIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroTIPO_LIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroTIPO_LIQUIDACION", new object[] {
                        obj}, this.buscarPrimeroTIPO_LIQUIDACIONOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroTIPO_LIQUIDACIONOperationCompleted(object arg) {
            if ((this.buscarPrimeroTIPO_LIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroTIPO_LIQUIDACIONCompleted(this, new buscarPrimeroTIPO_LIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarTIPO_LIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_LIQUIDACION[] buscarTIPO_LIQUIDACION(TIPO_LIQUIDACION obj) {
            object[] results = this.Invoke("buscarTIPO_LIQUIDACION", new object[] {
                        obj});
            return ((TIPO_LIQUIDACION[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj) {
            this.buscarTIPO_LIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj, object userState) {
            if ((this.buscarTIPO_LIQUIDACIONOperationCompleted == null)) {
                this.buscarTIPO_LIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarTIPO_LIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("buscarTIPO_LIQUIDACION", new object[] {
                        obj}, this.buscarTIPO_LIQUIDACIONOperationCompleted, userState);
        }
        
        private void OnbuscarTIPO_LIQUIDACIONOperationCompleted(object arg) {
            if ((this.buscarTIPO_LIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarTIPO_LIQUIDACIONCompleted(this, new buscarTIPO_LIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarTIPO_LIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_LIQUIDACION[] listarTIPO_LIQUIDACION() {
            object[] results = this.Invoke("listarTIPO_LIQUIDACION", new object[0]);
            return ((TIPO_LIQUIDACION[])(results[0]));
        }
        
        /// <remarks/>
        public void listarTIPO_LIQUIDACIONAsync() {
            this.listarTIPO_LIQUIDACIONAsync(null);
        }
        
        /// <remarks/>
        public void listarTIPO_LIQUIDACIONAsync(object userState) {
            if ((this.listarTIPO_LIQUIDACIONOperationCompleted == null)) {
                this.listarTIPO_LIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarTIPO_LIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("listarTIPO_LIQUIDACION", new object[0], this.listarTIPO_LIQUIDACIONOperationCompleted, userState);
        }
        
        private void OnlistarTIPO_LIQUIDACIONOperationCompleted(object arg) {
            if ((this.listarTIPO_LIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarTIPO_LIQUIDACIONCompleted(this, new listarTIPO_LIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarTIPO_LIQUIDACION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarTIPO_LIQUIDACION(TIPO_LIQUIDACION obj) {
            object[] results = this.Invoke("eliminarTIPO_LIQUIDACION", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj) {
            this.eliminarTIPO_LIQUIDACIONAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarTIPO_LIQUIDACIONAsync(TIPO_LIQUIDACION obj, object userState) {
            if ((this.eliminarTIPO_LIQUIDACIONOperationCompleted == null)) {
                this.eliminarTIPO_LIQUIDACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTIPO_LIQUIDACIONOperationCompleted);
            }
            this.InvokeAsync("eliminarTIPO_LIQUIDACION", new object[] {
                        obj}, this.eliminarTIPO_LIQUIDACIONOperationCompleted, userState);
        }
        
        private void OneliminarTIPO_LIQUIDACIONOperationCompleted(object arg) {
            if ((this.eliminarTIPO_LIQUIDACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTIPO_LIQUIDACIONCompleted(this, new eliminarTIPO_LIQUIDACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TIPO_LIQUIDACION {
        
        private int idField;
        
        private string tIPOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearTIPO_LIQUIDACIONCompletedEventHandler(object sender, crearTIPO_LIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearTIPO_LIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearTIPO_LIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_LIQUIDACION Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_LIQUIDACION)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarTIPO_LIQUIDACIONCompletedEventHandler(object sender, editarTIPO_LIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarTIPO_LIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarTIPO_LIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroTIPO_LIQUIDACIONCompletedEventHandler(object sender, buscarPrimeroTIPO_LIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroTIPO_LIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroTIPO_LIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_LIQUIDACION Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_LIQUIDACION)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarTIPO_LIQUIDACIONCompletedEventHandler(object sender, buscarTIPO_LIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarTIPO_LIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarTIPO_LIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_LIQUIDACION[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_LIQUIDACION[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarTIPO_LIQUIDACIONCompletedEventHandler(object sender, listarTIPO_LIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarTIPO_LIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarTIPO_LIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_LIQUIDACION[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_LIQUIDACION[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarTIPO_LIQUIDACIONCompletedEventHandler(object sender, eliminarTIPO_LIQUIDACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTIPO_LIQUIDACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTIPO_LIQUIDACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591