//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosTIPO_DOCUMENTO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosTIPO_DOCUMENTOSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosTIPO_DOCUMENTO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearTIPO_DOCUMENTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarTIPO_DOCUMENTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroTIPO_DOCUMENTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarTIPO_DOCUMENTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarTIPO_DOCUMENTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTIPO_DOCUMENTOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosTIPO_DOCUMENTO() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosTIPO_DOCUMENTO_ServiciosTIPO_DOCUMENTO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearTIPO_DOCUMENTOCompletedEventHandler crearTIPO_DOCUMENTOCompleted;
        
        /// <remarks/>
        public event editarTIPO_DOCUMENTOCompletedEventHandler editarTIPO_DOCUMENTOCompleted;
        
        /// <remarks/>
        public event buscarPrimeroTIPO_DOCUMENTOCompletedEventHandler buscarPrimeroTIPO_DOCUMENTOCompleted;
        
        /// <remarks/>
        public event buscarTIPO_DOCUMENTOCompletedEventHandler buscarTIPO_DOCUMENTOCompleted;
        
        /// <remarks/>
        public event listarTIPO_DOCUMENTOCompletedEventHandler listarTIPO_DOCUMENTOCompleted;
        
        /// <remarks/>
        public event eliminarTIPO_DOCUMENTOCompletedEventHandler eliminarTIPO_DOCUMENTOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearTIPO_DOCUMENTO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_DOCUMENTO crearTIPO_DOCUMENTO(TIPO_DOCUMENTO obj) {
            object[] results = this.Invoke("crearTIPO_DOCUMENTO", new object[] {
                        obj});
            return ((TIPO_DOCUMENTO)(results[0]));
        }
        
        /// <remarks/>
        public void crearTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj) {
            this.crearTIPO_DOCUMENTOAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj, object userState) {
            if ((this.crearTIPO_DOCUMENTOOperationCompleted == null)) {
                this.crearTIPO_DOCUMENTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearTIPO_DOCUMENTOOperationCompleted);
            }
            this.InvokeAsync("crearTIPO_DOCUMENTO", new object[] {
                        obj}, this.crearTIPO_DOCUMENTOOperationCompleted, userState);
        }
        
        private void OncrearTIPO_DOCUMENTOOperationCompleted(object arg) {
            if ((this.crearTIPO_DOCUMENTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearTIPO_DOCUMENTOCompleted(this, new crearTIPO_DOCUMENTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarTIPO_DOCUMENTO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarTIPO_DOCUMENTO(TIPO_DOCUMENTO obj) {
            object[] results = this.Invoke("editarTIPO_DOCUMENTO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj) {
            this.editarTIPO_DOCUMENTOAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj, object userState) {
            if ((this.editarTIPO_DOCUMENTOOperationCompleted == null)) {
                this.editarTIPO_DOCUMENTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarTIPO_DOCUMENTOOperationCompleted);
            }
            this.InvokeAsync("editarTIPO_DOCUMENTO", new object[] {
                        obj}, this.editarTIPO_DOCUMENTOOperationCompleted, userState);
        }
        
        private void OneditarTIPO_DOCUMENTOOperationCompleted(object arg) {
            if ((this.editarTIPO_DOCUMENTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarTIPO_DOCUMENTOCompleted(this, new editarTIPO_DOCUMENTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroTIPO_DOCUMENTO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_DOCUMENTO buscarPrimeroTIPO_DOCUMENTO(TIPO_DOCUMENTO obj) {
            object[] results = this.Invoke("buscarPrimeroTIPO_DOCUMENTO", new object[] {
                        obj});
            return ((TIPO_DOCUMENTO)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj) {
            this.buscarPrimeroTIPO_DOCUMENTOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj, object userState) {
            if ((this.buscarPrimeroTIPO_DOCUMENTOOperationCompleted == null)) {
                this.buscarPrimeroTIPO_DOCUMENTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroTIPO_DOCUMENTOOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroTIPO_DOCUMENTO", new object[] {
                        obj}, this.buscarPrimeroTIPO_DOCUMENTOOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroTIPO_DOCUMENTOOperationCompleted(object arg) {
            if ((this.buscarPrimeroTIPO_DOCUMENTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroTIPO_DOCUMENTOCompleted(this, new buscarPrimeroTIPO_DOCUMENTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarTIPO_DOCUMENTO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_DOCUMENTO[] buscarTIPO_DOCUMENTO(TIPO_DOCUMENTO obj) {
            object[] results = this.Invoke("buscarTIPO_DOCUMENTO", new object[] {
                        obj});
            return ((TIPO_DOCUMENTO[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj) {
            this.buscarTIPO_DOCUMENTOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj, object userState) {
            if ((this.buscarTIPO_DOCUMENTOOperationCompleted == null)) {
                this.buscarTIPO_DOCUMENTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarTIPO_DOCUMENTOOperationCompleted);
            }
            this.InvokeAsync("buscarTIPO_DOCUMENTO", new object[] {
                        obj}, this.buscarTIPO_DOCUMENTOOperationCompleted, userState);
        }
        
        private void OnbuscarTIPO_DOCUMENTOOperationCompleted(object arg) {
            if ((this.buscarTIPO_DOCUMENTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarTIPO_DOCUMENTOCompleted(this, new buscarTIPO_DOCUMENTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarTIPO_DOCUMENTO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIPO_DOCUMENTO[] listarTIPO_DOCUMENTO() {
            object[] results = this.Invoke("listarTIPO_DOCUMENTO", new object[0]);
            return ((TIPO_DOCUMENTO[])(results[0]));
        }
        
        /// <remarks/>
        public void listarTIPO_DOCUMENTOAsync() {
            this.listarTIPO_DOCUMENTOAsync(null);
        }
        
        /// <remarks/>
        public void listarTIPO_DOCUMENTOAsync(object userState) {
            if ((this.listarTIPO_DOCUMENTOOperationCompleted == null)) {
                this.listarTIPO_DOCUMENTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarTIPO_DOCUMENTOOperationCompleted);
            }
            this.InvokeAsync("listarTIPO_DOCUMENTO", new object[0], this.listarTIPO_DOCUMENTOOperationCompleted, userState);
        }
        
        private void OnlistarTIPO_DOCUMENTOOperationCompleted(object arg) {
            if ((this.listarTIPO_DOCUMENTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarTIPO_DOCUMENTOCompleted(this, new listarTIPO_DOCUMENTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarTIPO_DOCUMENTO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarTIPO_DOCUMENTO(TIPO_DOCUMENTO obj) {
            object[] results = this.Invoke("eliminarTIPO_DOCUMENTO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj) {
            this.eliminarTIPO_DOCUMENTOAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarTIPO_DOCUMENTOAsync(TIPO_DOCUMENTO obj, object userState) {
            if ((this.eliminarTIPO_DOCUMENTOOperationCompleted == null)) {
                this.eliminarTIPO_DOCUMENTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTIPO_DOCUMENTOOperationCompleted);
            }
            this.InvokeAsync("eliminarTIPO_DOCUMENTO", new object[] {
                        obj}, this.eliminarTIPO_DOCUMENTOOperationCompleted, userState);
        }
        
        private void OneliminarTIPO_DOCUMENTOOperationCompleted(object arg) {
            if ((this.eliminarTIPO_DOCUMENTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTIPO_DOCUMENTOCompleted(this, new eliminarTIPO_DOCUMENTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TIPO_DOCUMENTO {
        
        private int idField;
        
        private string tIPOField;
        
        private string aBREVIACIONField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
            }
        }
        
        /// <remarks/>
        public string ABREVIACION {
            get {
                return this.aBREVIACIONField;
            }
            set {
                this.aBREVIACIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearTIPO_DOCUMENTOCompletedEventHandler(object sender, crearTIPO_DOCUMENTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearTIPO_DOCUMENTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearTIPO_DOCUMENTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_DOCUMENTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_DOCUMENTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarTIPO_DOCUMENTOCompletedEventHandler(object sender, editarTIPO_DOCUMENTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarTIPO_DOCUMENTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarTIPO_DOCUMENTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroTIPO_DOCUMENTOCompletedEventHandler(object sender, buscarPrimeroTIPO_DOCUMENTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroTIPO_DOCUMENTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroTIPO_DOCUMENTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_DOCUMENTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_DOCUMENTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarTIPO_DOCUMENTOCompletedEventHandler(object sender, buscarTIPO_DOCUMENTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarTIPO_DOCUMENTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarTIPO_DOCUMENTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_DOCUMENTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_DOCUMENTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarTIPO_DOCUMENTOCompletedEventHandler(object sender, listarTIPO_DOCUMENTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarTIPO_DOCUMENTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarTIPO_DOCUMENTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIPO_DOCUMENTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIPO_DOCUMENTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarTIPO_DOCUMENTOCompletedEventHandler(object sender, eliminarTIPO_DOCUMENTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTIPO_DOCUMENTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTIPO_DOCUMENTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591