//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.WSServiciosRECIBO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosRECIBOSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosRECIBO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearRECIBOOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarRECIBOOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarRECIBOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroRECIBOOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarRECIBOOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarRECIBOOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarRECIBOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosRECIBO() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_WSServiciosRECIBO_ServiciosRECIBO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearRECIBOCompletedEventHandler crearRECIBOCompleted;
        
        /// <remarks/>
        public event generarRECIBOCompletedEventHandler generarRECIBOCompleted;
        
        /// <remarks/>
        public event editarRECIBOCompletedEventHandler editarRECIBOCompleted;
        
        /// <remarks/>
        public event buscarPrimeroRECIBOCompletedEventHandler buscarPrimeroRECIBOCompleted;
        
        /// <remarks/>
        public event buscarRECIBOCompletedEventHandler buscarRECIBOCompleted;
        
        /// <remarks/>
        public event listarRECIBOCompletedEventHandler listarRECIBOCompleted;
        
        /// <remarks/>
        public event eliminarRECIBOCompletedEventHandler eliminarRECIBOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RECIBO crearRECIBO(RECIBO obj) {
            object[] results = this.Invoke("crearRECIBO", new object[] {
                        obj});
            return ((RECIBO)(results[0]));
        }
        
        /// <remarks/>
        public void crearRECIBOAsync(RECIBO obj) {
            this.crearRECIBOAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearRECIBOAsync(RECIBO obj, object userState) {
            if ((this.crearRECIBOOperationCompleted == null)) {
                this.crearRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearRECIBOOperationCompleted);
            }
            this.InvokeAsync("crearRECIBO", new object[] {
                        obj}, this.crearRECIBOOperationCompleted, userState);
        }
        
        private void OncrearRECIBOOperationCompleted(object arg) {
            if ((this.crearRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearRECIBOCompleted(this, new crearRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/generarRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RECIBO generarRECIBO(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente) {
            object[] results = this.Invoke("generarRECIBO", new object[] {
                        liquidacion,
                        lstDetalles,
                        myCliente});
            return ((RECIBO)(results[0]));
        }
        
        /// <remarks/>
        public void generarRECIBOAsync(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente) {
            this.generarRECIBOAsync(liquidacion, lstDetalles, myCliente, null);
        }
        
        /// <remarks/>
        public void generarRECIBOAsync(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente, object userState) {
            if ((this.generarRECIBOOperationCompleted == null)) {
                this.generarRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarRECIBOOperationCompleted);
            }
            this.InvokeAsync("generarRECIBO", new object[] {
                        liquidacion,
                        lstDetalles,
                        myCliente}, this.generarRECIBOOperationCompleted, userState);
        }
        
        private void OngenerarRECIBOOperationCompleted(object arg) {
            if ((this.generarRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarRECIBOCompleted(this, new generarRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarRECIBO(RECIBO obj) {
            object[] results = this.Invoke("editarRECIBO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarRECIBOAsync(RECIBO obj) {
            this.editarRECIBOAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarRECIBOAsync(RECIBO obj, object userState) {
            if ((this.editarRECIBOOperationCompleted == null)) {
                this.editarRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarRECIBOOperationCompleted);
            }
            this.InvokeAsync("editarRECIBO", new object[] {
                        obj}, this.editarRECIBOOperationCompleted, userState);
        }
        
        private void OneditarRECIBOOperationCompleted(object arg) {
            if ((this.editarRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarRECIBOCompleted(this, new editarRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RECIBO buscarPrimeroRECIBO(RECIBO obj) {
            object[] results = this.Invoke("buscarPrimeroRECIBO", new object[] {
                        obj});
            return ((RECIBO)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroRECIBOAsync(RECIBO obj) {
            this.buscarPrimeroRECIBOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroRECIBOAsync(RECIBO obj, object userState) {
            if ((this.buscarPrimeroRECIBOOperationCompleted == null)) {
                this.buscarPrimeroRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroRECIBOOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroRECIBO", new object[] {
                        obj}, this.buscarPrimeroRECIBOOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroRECIBOOperationCompleted(object arg) {
            if ((this.buscarPrimeroRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroRECIBOCompleted(this, new buscarPrimeroRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RECIBO[] buscarRECIBO(RECIBO obj) {
            object[] results = this.Invoke("buscarRECIBO", new object[] {
                        obj});
            return ((RECIBO[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarRECIBOAsync(RECIBO obj) {
            this.buscarRECIBOAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarRECIBOAsync(RECIBO obj, object userState) {
            if ((this.buscarRECIBOOperationCompleted == null)) {
                this.buscarRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarRECIBOOperationCompleted);
            }
            this.InvokeAsync("buscarRECIBO", new object[] {
                        obj}, this.buscarRECIBOOperationCompleted, userState);
        }
        
        private void OnbuscarRECIBOOperationCompleted(object arg) {
            if ((this.buscarRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarRECIBOCompleted(this, new buscarRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RECIBO[] listarRECIBO() {
            object[] results = this.Invoke("listarRECIBO", new object[0]);
            return ((RECIBO[])(results[0]));
        }
        
        /// <remarks/>
        public void listarRECIBOAsync() {
            this.listarRECIBOAsync(null);
        }
        
        /// <remarks/>
        public void listarRECIBOAsync(object userState) {
            if ((this.listarRECIBOOperationCompleted == null)) {
                this.listarRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarRECIBOOperationCompleted);
            }
            this.InvokeAsync("listarRECIBO", new object[0], this.listarRECIBOOperationCompleted, userState);
        }
        
        private void OnlistarRECIBOOperationCompleted(object arg) {
            if ((this.listarRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarRECIBOCompleted(this, new listarRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarRECIBO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarRECIBO(RECIBO obj) {
            object[] results = this.Invoke("eliminarRECIBO", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarRECIBOAsync(RECIBO obj) {
            this.eliminarRECIBOAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarRECIBOAsync(RECIBO obj, object userState) {
            if ((this.eliminarRECIBOOperationCompleted == null)) {
                this.eliminarRECIBOOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarRECIBOOperationCompleted);
            }
            this.InvokeAsync("eliminarRECIBO", new object[] {
                        obj}, this.eliminarRECIBOOperationCompleted, userState);
        }
        
        private void OneliminarRECIBOOperationCompleted(object arg) {
            if ((this.eliminarRECIBOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarRECIBOCompleted(this, new eliminarRECIBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RECIBO {
        
        private int idField;
        
        private int iD_LIQUIDACIONField;
        
        private int iD_ESTADOField;
        
        private string nUMERO_RECIBOField;
        
        private System.DateTime fECHA_RECIBOField;
        
        private System.DateTime fECHA_REGISTRO_PAGOField;
        
        private System.DateTime fECHA_PAGOField;
        
        private float vALORField;
        
        private System.DateTime fECHA_VENCIMIENTOField;
        
        private System.DateTime fECHA_ENTRAMITEField;
        
        private System.DateTime fECHA_ANULADOField;
        
        private System.DateTime fECHA_PAGOANULADOField;
        
        private System.DateTime fECHA_PROCESADOField;
        
        private byte[] aRCHIVO_FISICOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_LIQUIDACION {
            get {
                return this.iD_LIQUIDACIONField;
            }
            set {
                this.iD_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public int ID_ESTADO {
            get {
                return this.iD_ESTADOField;
            }
            set {
                this.iD_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_RECIBO {
            get {
                return this.nUMERO_RECIBOField;
            }
            set {
                this.nUMERO_RECIBOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_RECIBO {
            get {
                return this.fECHA_RECIBOField;
            }
            set {
                this.fECHA_RECIBOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_REGISTRO_PAGO {
            get {
                return this.fECHA_REGISTRO_PAGOField;
            }
            set {
                this.fECHA_REGISTRO_PAGOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_PAGO {
            get {
                return this.fECHA_PAGOField;
            }
            set {
                this.fECHA_PAGOField = value;
            }
        }
        
        /// <remarks/>
        public float VALOR {
            get {
                return this.vALORField;
            }
            set {
                this.vALORField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_VENCIMIENTO {
            get {
                return this.fECHA_VENCIMIENTOField;
            }
            set {
                this.fECHA_VENCIMIENTOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_ENTRAMITE {
            get {
                return this.fECHA_ENTRAMITEField;
            }
            set {
                this.fECHA_ENTRAMITEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_ANULADO {
            get {
                return this.fECHA_ANULADOField;
            }
            set {
                this.fECHA_ANULADOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_PAGOANULADO {
            get {
                return this.fECHA_PAGOANULADOField;
            }
            set {
                this.fECHA_PAGOANULADOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_PROCESADO {
            get {
                return this.fECHA_PROCESADOField;
            }
            set {
                this.fECHA_PROCESADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ARCHIVO_FISICO {
            get {
                return this.aRCHIVO_FISICOField;
            }
            set {
                this.aRCHIVO_FISICOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VIEW_CLIENTE {
        
        private int idField;
        
        private string tIPO_DOCUMENTOField;
        
        private string iDENTIFICACIONField;
        
        private string nOMBRESField;
        
        private string aPELLIDOSField;
        
        private string dIRECCIONField;
        
        private string cIUDADField;
        
        private string dEPARTAMENTOField;
        
        private string gENEROField;
        
        private string tELEFONOField;
        
        private string cELULARField;
        
        private string cORREOField;
        
        private string fECHA_NACIMIENTOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO_DOCUMENTO {
            get {
                return this.tIPO_DOCUMENTOField;
            }
            set {
                this.tIPO_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string IDENTIFICACION {
            get {
                return this.iDENTIFICACIONField;
            }
            set {
                this.iDENTIFICACIONField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <remarks/>
        public string APELLIDOS {
            get {
                return this.aPELLIDOSField;
            }
            set {
                this.aPELLIDOSField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        public string CIUDAD {
            get {
                return this.cIUDADField;
            }
            set {
                this.cIUDADField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTAMENTO {
            get {
                return this.dEPARTAMENTOField;
            }
            set {
                this.dEPARTAMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string GENERO {
            get {
                return this.gENEROField;
            }
            set {
                this.gENEROField = value;
            }
        }
        
        /// <remarks/>
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <remarks/>
        public string CELULAR {
            get {
                return this.cELULARField;
            }
            set {
                this.cELULARField = value;
            }
        }
        
        /// <remarks/>
        public string CORREO {
            get {
                return this.cORREOField;
            }
            set {
                this.cORREOField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_NACIMIENTO {
            get {
                return this.fECHA_NACIMIENTOField;
            }
            set {
                this.fECHA_NACIMIENTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LIQUIDACION_DETALLE {
        
        private int idField;
        
        private int iD_LIQUIDACIONField;
        
        private int iD_TARIFA_DETALLEField;
        
        private float vALOR_CONCEPTOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_LIQUIDACION {
            get {
                return this.iD_LIQUIDACIONField;
            }
            set {
                this.iD_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA_DETALLE {
            get {
                return this.iD_TARIFA_DETALLEField;
            }
            set {
                this.iD_TARIFA_DETALLEField = value;
            }
        }
        
        /// <remarks/>
        public float VALOR_CONCEPTO {
            get {
                return this.vALOR_CONCEPTOField;
            }
            set {
                this.vALOR_CONCEPTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LIQUIDACION {
        
        private int idField;
        
        private int iD_CLIENTEField;
        
        private int iD_TIPO_LIQUIDACIONField;
        
        private System.DateTime fECHA_LIQUIDACIONField;
        
        private float tOTALField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_CLIENTE {
            get {
                return this.iD_CLIENTEField;
            }
            set {
                this.iD_CLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TIPO_LIQUIDACION {
            get {
                return this.iD_TIPO_LIQUIDACIONField;
            }
            set {
                this.iD_TIPO_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_LIQUIDACION {
            get {
                return this.fECHA_LIQUIDACIONField;
            }
            set {
                this.fECHA_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public float TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearRECIBOCompletedEventHandler(object sender, crearRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RECIBO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RECIBO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void generarRECIBOCompletedEventHandler(object sender, generarRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RECIBO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RECIBO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarRECIBOCompletedEventHandler(object sender, editarRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroRECIBOCompletedEventHandler(object sender, buscarPrimeroRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RECIBO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RECIBO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarRECIBOCompletedEventHandler(object sender, buscarRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RECIBO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RECIBO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarRECIBOCompletedEventHandler(object sender, listarRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RECIBO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RECIBO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarRECIBOCompletedEventHandler(object sender, eliminarRECIBOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarRECIBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarRECIBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591