//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EscuelaConduccion.wsServiciosFACTURA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosFACTURASoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosFACTURA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearFACTURAOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarFACTURAOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarFACTURAOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPrimeroFACTURAOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarFACTURAOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarFACTURAOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarFACTURAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosFACTURA() {
            this.Url = global::EscuelaConduccion.Properties.Settings.Default.EscuelaConduccion_wsServiciosFACTURA_ServiciosFACTURA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearFACTURACompletedEventHandler crearFACTURACompleted;
        
        /// <remarks/>
        public event generarFACTURACompletedEventHandler generarFACTURACompleted;
        
        /// <remarks/>
        public event editarFACTURACompletedEventHandler editarFACTURACompleted;
        
        /// <remarks/>
        public event buscarPrimeroFACTURACompletedEventHandler buscarPrimeroFACTURACompleted;
        
        /// <remarks/>
        public event buscarFACTURACompletedEventHandler buscarFACTURACompleted;
        
        /// <remarks/>
        public event listarFACTURACompletedEventHandler listarFACTURACompleted;
        
        /// <remarks/>
        public event eliminarFACTURACompletedEventHandler eliminarFACTURACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crearFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA crearFACTURA(FACTURA obj) {
            object[] results = this.Invoke("crearFACTURA", new object[] {
                        obj});
            return ((FACTURA)(results[0]));
        }
        
        /// <remarks/>
        public void crearFACTURAAsync(FACTURA obj) {
            this.crearFACTURAAsync(obj, null);
        }
        
        /// <remarks/>
        public void crearFACTURAAsync(FACTURA obj, object userState) {
            if ((this.crearFACTURAOperationCompleted == null)) {
                this.crearFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearFACTURAOperationCompleted);
            }
            this.InvokeAsync("crearFACTURA", new object[] {
                        obj}, this.crearFACTURAOperationCompleted, userState);
        }
        
        private void OncrearFACTURAOperationCompleted(object arg) {
            if ((this.crearFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearFACTURACompleted(this, new crearFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/generarFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA generarFACTURA(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente, Facturaconsecutivodetalle rango) {
            object[] results = this.Invoke("generarFACTURA", new object[] {
                        liquidacion,
                        lstDetalles,
                        myCliente,
                        rango});
            return ((FACTURA)(results[0]));
        }
        
        /// <remarks/>
        public void generarFACTURAAsync(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente, Facturaconsecutivodetalle rango) {
            this.generarFACTURAAsync(liquidacion, lstDetalles, myCliente, rango, null);
        }
        
        /// <remarks/>
        public void generarFACTURAAsync(LIQUIDACION liquidacion, LIQUIDACION_DETALLE[] lstDetalles, VIEW_CLIENTE myCliente, Facturaconsecutivodetalle rango, object userState) {
            if ((this.generarFACTURAOperationCompleted == null)) {
                this.generarFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarFACTURAOperationCompleted);
            }
            this.InvokeAsync("generarFACTURA", new object[] {
                        liquidacion,
                        lstDetalles,
                        myCliente,
                        rango}, this.generarFACTURAOperationCompleted, userState);
        }
        
        private void OngenerarFACTURAOperationCompleted(object arg) {
            if ((this.generarFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarFACTURACompleted(this, new generarFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool editarFACTURA(FACTURA obj) {
            object[] results = this.Invoke("editarFACTURA", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarFACTURAAsync(FACTURA obj) {
            this.editarFACTURAAsync(obj, null);
        }
        
        /// <remarks/>
        public void editarFACTURAAsync(FACTURA obj, object userState) {
            if ((this.editarFACTURAOperationCompleted == null)) {
                this.editarFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarFACTURAOperationCompleted);
            }
            this.InvokeAsync("editarFACTURA", new object[] {
                        obj}, this.editarFACTURAOperationCompleted, userState);
        }
        
        private void OneditarFACTURAOperationCompleted(object arg) {
            if ((this.editarFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarFACTURACompleted(this, new editarFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPrimeroFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA buscarPrimeroFACTURA(FACTURA obj) {
            object[] results = this.Invoke("buscarPrimeroFACTURA", new object[] {
                        obj});
            return ((FACTURA)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPrimeroFACTURAAsync(FACTURA obj) {
            this.buscarPrimeroFACTURAAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarPrimeroFACTURAAsync(FACTURA obj, object userState) {
            if ((this.buscarPrimeroFACTURAOperationCompleted == null)) {
                this.buscarPrimeroFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPrimeroFACTURAOperationCompleted);
            }
            this.InvokeAsync("buscarPrimeroFACTURA", new object[] {
                        obj}, this.buscarPrimeroFACTURAOperationCompleted, userState);
        }
        
        private void OnbuscarPrimeroFACTURAOperationCompleted(object arg) {
            if ((this.buscarPrimeroFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPrimeroFACTURACompleted(this, new buscarPrimeroFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA[] buscarFACTURA(FACTURA obj) {
            object[] results = this.Invoke("buscarFACTURA", new object[] {
                        obj});
            return ((FACTURA[])(results[0]));
        }
        
        /// <remarks/>
        public void buscarFACTURAAsync(FACTURA obj) {
            this.buscarFACTURAAsync(obj, null);
        }
        
        /// <remarks/>
        public void buscarFACTURAAsync(FACTURA obj, object userState) {
            if ((this.buscarFACTURAOperationCompleted == null)) {
                this.buscarFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarFACTURAOperationCompleted);
            }
            this.InvokeAsync("buscarFACTURA", new object[] {
                        obj}, this.buscarFACTURAOperationCompleted, userState);
        }
        
        private void OnbuscarFACTURAOperationCompleted(object arg) {
            if ((this.buscarFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarFACTURACompleted(this, new buscarFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FACTURA[] listarFACTURA() {
            object[] results = this.Invoke("listarFACTURA", new object[0]);
            return ((FACTURA[])(results[0]));
        }
        
        /// <remarks/>
        public void listarFACTURAAsync() {
            this.listarFACTURAAsync(null);
        }
        
        /// <remarks/>
        public void listarFACTURAAsync(object userState) {
            if ((this.listarFACTURAOperationCompleted == null)) {
                this.listarFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarFACTURAOperationCompleted);
            }
            this.InvokeAsync("listarFACTURA", new object[0], this.listarFACTURAOperationCompleted, userState);
        }
        
        private void OnlistarFACTURAOperationCompleted(object arg) {
            if ((this.listarFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarFACTURACompleted(this, new listarFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarFACTURA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarFACTURA(FACTURA obj) {
            object[] results = this.Invoke("eliminarFACTURA", new object[] {
                        obj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarFACTURAAsync(FACTURA obj) {
            this.eliminarFACTURAAsync(obj, null);
        }
        
        /// <remarks/>
        public void eliminarFACTURAAsync(FACTURA obj, object userState) {
            if ((this.eliminarFACTURAOperationCompleted == null)) {
                this.eliminarFACTURAOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarFACTURAOperationCompleted);
            }
            this.InvokeAsync("eliminarFACTURA", new object[] {
                        obj}, this.eliminarFACTURAOperationCompleted, userState);
        }
        
        private void OneliminarFACTURAOperationCompleted(object arg) {
            if ((this.eliminarFACTURACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarFACTURACompleted(this, new eliminarFACTURACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FACTURA {
        
        private int idField;
        
        private int iD_FACTURA_ESTADOField;
        
        private int iD_LIQUIDACIONField;
        
        private string nUMERO_FACTURAField;
        
        private string dISPONIBLEField;
        
        private byte[] aRCHIVO_FISICOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_FACTURA_ESTADO {
            get {
                return this.iD_FACTURA_ESTADOField;
            }
            set {
                this.iD_FACTURA_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public int ID_LIQUIDACION {
            get {
                return this.iD_LIQUIDACIONField;
            }
            set {
                this.iD_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_FACTURA {
            get {
                return this.nUMERO_FACTURAField;
            }
            set {
                this.nUMERO_FACTURAField = value;
            }
        }
        
        /// <remarks/>
        public string DISPONIBLE {
            get {
                return this.dISPONIBLEField;
            }
            set {
                this.dISPONIBLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ARCHIVO_FISICO {
            get {
                return this.aRCHIVO_FISICOField;
            }
            set {
                this.aRCHIVO_FISICOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Facturaconsecutivodetalle {
        
        private int idField;
        
        private int iD_FACTURACONSECUTIVOField;
        
        private double cONSECUTIVOField;
        
        private string dISPONIBLEField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_FACTURACONSECUTIVO {
            get {
                return this.iD_FACTURACONSECUTIVOField;
            }
            set {
                this.iD_FACTURACONSECUTIVOField = value;
            }
        }
        
        /// <remarks/>
        public double CONSECUTIVO {
            get {
                return this.cONSECUTIVOField;
            }
            set {
                this.cONSECUTIVOField = value;
            }
        }
        
        /// <remarks/>
        public string DISPONIBLE {
            get {
                return this.dISPONIBLEField;
            }
            set {
                this.dISPONIBLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VIEW_CLIENTE {
        
        private int idField;
        
        private string tIPO_DOCUMENTOField;
        
        private string iDENTIFICACIONField;
        
        private string nOMBRESField;
        
        private string aPELLIDOSField;
        
        private string dIRECCIONField;
        
        private string cIUDADField;
        
        private string dEPARTAMENTOField;
        
        private string gENEROField;
        
        private string tELEFONOField;
        
        private string cELULARField;
        
        private string cORREOField;
        
        private string fECHA_NACIMIENTOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO_DOCUMENTO {
            get {
                return this.tIPO_DOCUMENTOField;
            }
            set {
                this.tIPO_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string IDENTIFICACION {
            get {
                return this.iDENTIFICACIONField;
            }
            set {
                this.iDENTIFICACIONField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <remarks/>
        public string APELLIDOS {
            get {
                return this.aPELLIDOSField;
            }
            set {
                this.aPELLIDOSField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        public string CIUDAD {
            get {
                return this.cIUDADField;
            }
            set {
                this.cIUDADField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTAMENTO {
            get {
                return this.dEPARTAMENTOField;
            }
            set {
                this.dEPARTAMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string GENERO {
            get {
                return this.gENEROField;
            }
            set {
                this.gENEROField = value;
            }
        }
        
        /// <remarks/>
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <remarks/>
        public string CELULAR {
            get {
                return this.cELULARField;
            }
            set {
                this.cELULARField = value;
            }
        }
        
        /// <remarks/>
        public string CORREO {
            get {
                return this.cORREOField;
            }
            set {
                this.cORREOField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_NACIMIENTO {
            get {
                return this.fECHA_NACIMIENTOField;
            }
            set {
                this.fECHA_NACIMIENTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LIQUIDACION_DETALLE {
        
        private int idField;
        
        private int iD_LIQUIDACIONField;
        
        private int iD_TARIFA_DETALLEField;
        
        private float vALOR_CONCEPTOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_LIQUIDACION {
            get {
                return this.iD_LIQUIDACIONField;
            }
            set {
                this.iD_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TARIFA_DETALLE {
            get {
                return this.iD_TARIFA_DETALLEField;
            }
            set {
                this.iD_TARIFA_DETALLEField = value;
            }
        }
        
        /// <remarks/>
        public float VALOR_CONCEPTO {
            get {
                return this.vALOR_CONCEPTOField;
            }
            set {
                this.vALOR_CONCEPTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LIQUIDACION {
        
        private int idField;
        
        private int iD_CLIENTEField;
        
        private int iD_TIPO_LIQUIDACIONField;
        
        private System.DateTime fECHA_LIQUIDACIONField;
        
        private float tOTALField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ID_CLIENTE {
            get {
                return this.iD_CLIENTEField;
            }
            set {
                this.iD_CLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TIPO_LIQUIDACION {
            get {
                return this.iD_TIPO_LIQUIDACIONField;
            }
            set {
                this.iD_TIPO_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHA_LIQUIDACION {
            get {
                return this.fECHA_LIQUIDACIONField;
            }
            set {
                this.fECHA_LIQUIDACIONField = value;
            }
        }
        
        /// <remarks/>
        public float TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearFACTURACompletedEventHandler(object sender, crearFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void generarFACTURACompletedEventHandler(object sender, generarFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarFACTURACompletedEventHandler(object sender, editarFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPrimeroFACTURACompletedEventHandler(object sender, buscarPrimeroFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPrimeroFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPrimeroFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarFACTURACompletedEventHandler(object sender, buscarFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarFACTURACompletedEventHandler(object sender, listarFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FACTURA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FACTURA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarFACTURACompletedEventHandler(object sender, eliminarFACTURACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarFACTURACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarFACTURACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591